### ISSUE TITLE
Provide validator tests for the initializer/interceptor closures

### ISSUE THREAD

**Issue by Ocramius** [Ocramius/ProxyManager#15]
Currently, the initializer and interceptor closures are not checked for validity. Doing it at runtime is a no-go, but allowing the users to test them is acceptable if we provide a test utility that can handle it.

**Comment by slash3b** [comment]
quick question @Ocramius — this is still valid and I can dig in ?

**Comment by Ocramius** [comment]
The type declarations I added mostly fix this

**Comment by Ocramius** [comment]
I think this can be closed as "won't fix", since psalm takes care of the validation just fine :)
