### ISSUE TITLE
Proxy generation fails if magic methods are marked as final.

### ISSUE THREAD

**Issue by jmalloc** [Ocramius/ProxyManager#187]
The `PDO::__wakeup()` method is marked as final, but it looks like the final flag of magic methods is not checked as it is for other methods. Hence the code below produces a fatal error:

``` php
$factory = new ProxyManager\Factory\LazyLoadingValueHolderFactory();
$factory->createProxy(
    'PDO',
    function () {}
);
```

```
Fatal error: Cannot override final method PDO::__wakeup() in ... on line 5
```

**Comment by githoober** [comment]
Hi @Ocramius,

my question is whether a final method should instantiate a proxy. I have a strong feeling that it should. And because it cannot be overridden a different mechanism should be implemented to make it work.
Any thoughts on that?

**Comment by Ocramius** [comment]
> And because it cannot be overridden a different mechanism should be implemented to make it work.

It simply cannot be done. `final` is `final`, and that's perfectly ok. If you need to mock/proxy final classes, then you want to proxy their interface instead.

**Comment by githoober** [comment]
I agree with an argument about creating a proxy for a final class, but my question is about a regular not final class that can contain some final methods. Since a proxy should be instantiated by any public method, this should also include final public methods. Since overriding is not working in this case, a different way could be researched instead.

**Comment by Ocramius** [comment]
@githoober that depends on the proxy implementation. Right now, [we already proxy only methods that can be overridden](https://github.com/Ocramius/ProxyManager/blob/6e15877fc03cc211ce798d497a21208a44f7b726/src/ProxyManager/ProxyGenerator/LazyLoadingGhostGenerator.php#L88)

In some proxy implementations, the methods *need* to be all proxied, and therefore it is not possible to proceed with the code generation.
