### ISSUE TITLE
PHP Fatal error: Class '....PheanstalkProxyInterface' not found in '....ParameterGenerator.php'

### ISSUE THREAD

**Issue by inanzzz** [Ocramius/ProxyManager#228]
Hi,

I'm not sure if whether this is related to Ocramius or Leezy but when I try to install one or both of these packages with composer I'm getting error below. I tried certain version numbers for both packages but for some reason error won't go away. Any reason why?

Thanks

```
PHP Fatal error:  Class 'Leezy\pheanstalkBundle\Proxy\PheanstalkProxyInterface' not found in /var/www/html/local/fws/vendor/ocramius/proxy-manager/src/ProxyManager/Generator/ParameterGenerator.php on line 143
```

**Comment by blanchonvincent** [comment]
@inanzzz it seems not related to the proxy manager. Check your autoloading :)

**Comment by inanzzz** [comment]
What should I check about autoloading or how should it be?

This is my current one in composer.json:
```
    "autoload": {
        "psr-0": { "": "src/" }
    },
```

**Comment by Ocramius** [comment]
This is usually caused by something like following:

http://3v4l.org/FHMqM

Copied here for reference:

```php
<?php

class Foo { public function bar(Baz $baz) {} }

(new ReflectionParameter(['Foo', 'bar'], 'baz'))->getClass();
```

**Comment by inanzzz** [comment]
I've just read it but what should I do in order to sort this issue?

**Comment by Ocramius** [comment]
@inanzzz the problem with your example is that `PheanstalkProxyInterface` seems to not exist or be incorrectly namespaced.
