### ISSUE TITLE
Unnecessary doc block reflection

### ISSUE THREAD

**Issue by wpillar** [Ocramius/ProxyManager#229]
Was doing some profiling of an application that uses this library and noticed that this block of code: https://github.com/Ocramius/ProxyManager/blob/master/src/ProxyManager/Generator/MethodGenerator.php#L67-69 is one of the most expensive in my request cycle.

Upon further inspection, in my particular call stack, I noticed that the parent that calls `MethodGenerator::fromReflection()` is https://github.com/Ocramius/ProxyManager/blob/master/src/ProxyManager/ProxyGenerator/LazyLoadingValueHolder/MethodGenerator/LazyLoadingMethodInterceptor.php#L68 which calls the parent `MethodGenerator::fromReflection()` which does the doc block scanning only for it to be overridden with `{@inheritDoc}` anyway.

My question is, have I missed something or am I right in thinking that in my particular call stack the doc block scanning is pointless? And if so, how can I do away with it so it doesn't impact my performance? Happy to work on a PR to achieve this.

**Comment by Ocramius** [comment]
@wpillar this library does make heavy usage of reflection: code generation can be very slow, and we don't aim at optimizing it.

Instead, the generated code should be cached as explained in https://github.com/Ocramius/ProxyManager/blob/e1c4f811d3c4f89ea1fad9de7fb12cfb82fae813/docs/tuning-for-production.md

Consider trying that first :-)
