### ISSUE TITLE
Support for methods from suffixes and prefixes.

### ISSUE THREAD

**Issue by malukenho** [Ocramius/ProxyManager#236]
I think it is a good idea to support the proxy methods beginning or ending with certain word. For example, we have a very heavy class, and its most corrosive methods are the ones that start with `fetch *`, we can easily and at once carry out the operation without duplicating code.

**Comment by Ocramius** [comment]
As per discussion, the idea that @malukenho had is to allow things such as 

```php
$accessInterceptorFactory->createProxy(
    $object,
    ['*' => function () { echo 'catch all the methods!'; }]
);
```

While I like the idea, it seems like a needless addition to me

**Comment by malukenho** [comment]
@Ocramius I think in anything as:

```php
$accessInterceptorFactory->createProxy(
    $object,
    [
        'foo*' => function () { echo 'catch all the methods started by `foo`!'; },
        '*foo' => function () { echo 'catch all the methods finished by `foo`!'; }
    ]

);
```

**Comment by Ocramius** [comment]
Yeah, it's just that this sort of code can be implemented by wrapping another factory around it instead :)

**Comment by Ocramius** [comment]
I think the library should focus on solving the actual problem of intercepting, rather than providing utilities for how the factories should be used. Closing therefore, as this sort of API can be implemented in consumer libraries.
