### ISSUE TITLE
Support scalar type hints (PHP 7)

### ISSUE THREAD

**Issue by Ocramius** [Ocramius/ProxyManager#240]

**Comment by lisachenko** [comment]
:+1:

**Comment by malukenho** [comment]
:clap: :+1:

**Comment by malukenho** [comment]
Linking #241

**Comment by robfrawley** [comment]
:+1: !!!!!

**Comment by joshdifabio** [comment]
Is anyone planning to tackle this in the near future? Presumably return types also need supporting?

**Comment by Ocramius** [comment]
Needs fixing at zend-code level first, or else moving away from it (which
is a huge amount of work)

**Comment by Ocramius** [comment]
Zis is DONE!!!1

**Comment by Ocramius** [comment]
Ref: https://github.com/Ocramius/ProxyManager/commit/e4dcd297954a136b9964cf0c5198348e1a15916b

**Comment by joshdifabio** [comment]
Fantastic! Thank you very much.
