### ISSUE TITLE
Proxies definitions

### ISSUE THREAD

**Issue by malukenho** [Ocramius/ProxyManager#242]
Hi everyone,
I've been thinking about proxy definitions with object-oriented approach. The main objective of facilitating long term maintenance and can separate our proxies below a namespace, to facilitate use in some architectures.

So basically my idea is to have classes that define a proxy. And so we can generate from these previously written definitions.

``` php
interface ProxyDefinitionInterface
{
    public function canProxyClass();
    public function __invoke(); // ???
}
```
#### Example of a proxy definition class

``` php
<?php

namespace App\Proxy;

use App\Domain\Foo;
use ProxyManager\ProxyDefinitionInterface;

class FooGhostProxy implements ProxyDefinitionInterface
{
    /**
     * {@inheritDoc}
     */
    public function canProxyClass()
    {
        return Foo::class;
    }

    public function __invoke(/* Same proxy params we have actually */)
    {
         /* Definition */
    }
}
```

I thinks it's a good one too, because we can serialize and cache classes.
What do you think?

/cc @Ocramius

**Comment by Ocramius** [comment]
Few things:

 - the initial idea is good
 - the `__invoke` stuff should just disappear for now (a proxy definition is too broad to simplify it into a `callable`)
 - do we need one proxy definition per proxy type? Can we instead let ProxyManager decide which implementation to use based on passed in definition options?

**Comment by malukenho** [comment]
@Ocramius I think the user can write a definition to use, force a definition or just leave ProxyManager decide what use.

**Comment by Ocramius** [comment]
Can you provide a practical example on how this sort of API would be used?

To be specific, the current API is:

```php
$config = new ProxyManager\Configuration();
// change config here
$factory = new ProxyManager\Factory\SomeSortOfProxyFactory($config);

$proxy = $factory->createProxy($args, $options);
```

How can we improve this particular API?

**Comment by Ocramius** [comment]
Let's close this: proxy definitions are quite static, so I don't think we need to have a formal "definition object".

The current factories have a relatively straightforward API to create proxies, and kinda work with everything (and include type-checks too).

Ref: https://github.com/Ocramius/ProxyManager/tree/f65ae0f9dcbdd9d6ad3abb721a9e09c3d7d868a4/src/ProxyManager/Factory
