### ISSUE TITLE
Proxy Manager generated proxy class doesn't exist (ReflectionException)

### ISSUE THREAD

**Issue by jordi12100** [Ocramius/ProxyManager#244]
The following exception below is thrown in production environment. Development works fine without any issues/exceptions.

```
Uncaught Exception: Uncaught exception 'ReflectionException' with message 'Class ProxyManagerGeneratedProxy\__PM__\Page\Service\WebsiteService\Generated0c1861d4f47ce79393c1bdc3ce6b9dd5 does not exist' in /var/www/websites/jouwweb-v2/releases/20150717_161619/vendor/ocramius/proxy-manager/src/ProxyManager/Factory/AbstractBaseFactory.php:82
```

We use ProxyManager for Lazy loading services in ZF2. Temporary setting the write_proxy_files to false fixed the issue, but will slow down the application.

The files are written to the correct location, loading the file causes the crashes. May be an autoloading issue?
Any ideas what's going on? 

```php
    'lazy_services' => array(
        'class_map' => array(
            'SlmMail\Mail\Transport\MandrillTransport' => 'SlmMail\Mail\Transport\HttpTransport',
            'page_service_website' => 'Page\Service\WebsiteService',
            'plugin_news_service_news' => 'PluginNews\Service\NewsService'
        ),
        'write_proxy_files' => false,
        'proxies_target_dir' => __dir__ . '/../../../data/LazyServices/Proxy'
    ),
```

**Comment by Ocramius** [comment]
I would check if https://github.com/Ocramius/ProxyManager/blob/1.0.0/src/ProxyManager/Factory/AbstractBaseFactory.php#L75 is reached.

Also check that `__DIR__` (should be uppercase) and the existence of the proxy files

**Comment by jordi12100** [comment]
Hey @Ocramius,

Sorry for not getting back to you. This issue has been resolved. 
What exactly caused this issue is unknown, but a second deploy did resolve the issue.

It may have been a cache issue. Who knows...

-- Closing this issue

**Comment by Ocramius** [comment]
Thanks for reporting back!
