### ISSUE TITLE
Please check 1.0.1 tag

### ISSUE THREAD

**Issue by remicollet** [Ocramius/ProxyManager#253]
From https://github.com/Ocramius/ProxyManager/releases
* 1.0.0 tag is a80a39fac4fbd771aea7d3871929933a3a1bbf3e (Dec 2014)
* 1.0.1 tag is a80a39fac4fbd771aea7d3871929933a3a1bbf3e (the same)

So all commit from Aug 8-9 in 1.0.x branch are not applied... :(

**Comment by Ocramius** [comment]
@remicollet weird. Thanks for spotting it, I will bump the tag now.

**Comment by Ocramius** [comment]
@remicollet tagged 1.0.2. Thanks for being vigilant!

**Comment by remicollet** [comment]
;)
