### ISSUE TITLE
Revert #254, add integration test for options in factory logic

### ISSUE THREAD

**Issue by Ocramius** [Ocramius/ProxyManager#256]
#254 should be reverted, as the change actually removes functionality.

**Comment by malukenho** [comment]
@Ocramius what functionality was removed? If it was removed I think we have bad tests for this particular one.

**Comment by Ocramius** [comment]
@malukenho see discussion on #254 - need a unit test that expects the proxy generator to be given appropriate proxy options

**Comment by Ocramius** [comment]
Note: already reverted in Ocramius/ProxyManager#079399916eb7fba57aed709de2d63f104c696673 - now needs to be tested.

**Comment by localheinz** [comment]
@malukenho @Ocramius 

Sorry!

**Comment by Ocramius** [comment]
@localheinz no problem, you couldn't possibly know :-)

I considered changing the interface, but the BC break was a bit too big. Wondering if I can do it for 2.x :-\
