### ISSUE TITLE
Proxy __destruct issue

### ISSUE THREAD

**Issue by malinink** [Ocramius/ProxyManager#258]
Hi, 

I use PM in my ZF2 project, and all works correct, but I found one problem, fix me please if I am wrong.

I create Lazy Service and do not use it in particular case, but I call Proxy of that service which I pass to another object.

At the and of application someone (I suppose GC) call `__destruct` on object, that cause Proxy to init proxy object. It is not behaviour I expected.

So my question is: Is that normal?

Stack trace from exception from Factory of proxy object

```
#	Time	Memory	Function	Location
1	0.0519	3225752	ProxyManagerGeneratedProxy\__PM__\Zend\Log\Logger\Generated309fa39f737280002e5d4e613b403125->__destruct( )	../ProxyManagerGeneratedProxy__PM__ZendLogLoggerGenerated309fa39f737280002e5d4e613b403125.php:0
2	0.0520	3226280	__invoke ( )	../ProxyManagerGeneratedProxy__PM__ZendLogLoggerGenerated309fa39f737280002e5d4e613b403125.php:32
3	0.0520	3226392	Zend\ServiceManager\Proxy\LazyServiceFactory->Zend\ServiceManager\Proxy\{closure}( )	../ProxyManagerGeneratedProxy__PM__ZendLogLoggerGenerated309fa39f737280002e5d4e613b403125.php:32
4	0.0520	3226520	call_user_func ( )	../LazyServiceFactory.php:57
5	0.0520	3226552	Zend\ServiceManager\ServiceManager->Zend\ServiceManager\{closure}( )	../LazyServiceFactory.php:57
6	0.0520	3226552	Zend\ServiceManager\ServiceManager->doCreate( )	../ServiceManager.php:1194
7	0.0520	3226600	Zend\ServiceManager\ServiceManager->createFromFactory( )	../ServiceManager.php:638
8	0.0523	3235680	Zend\ServiceManager\ServiceManager->createServiceViaCallback( )	../ServiceManager.php:1097 
```

I thought that it will be better do not nothing at that case. (if proxy object is not instanced already)

**Comment by Ocramius** [comment]
@malinink since we can't have any assumption about what is contained in the `__destruct` logic, ProxyManager has to delegate the call, initializing therefore your object.

There is no workaround to this, as making `__destruct` no-op is potentially very dangerous.

**Comment by malinink** [comment]
@Ocramius Thank for the answer,

That sound like all proxy objects will be instanced at the end of application. I thought that main aim of proxy is preventing objects to be instanced if them are not used at particular case.

I will try to check that behaviour at another php version (current one is 5.5.9), at now all proxy objects instanced at the end, if they are not used in application.

**Comment by Ocramius** [comment]
> That sound like all proxy objects will be instanced at the end of application.

Only if they were required in first place

 > I thought that main aim of proxy is preventing objects to be instanced if them are not used at particular case.

A destructor is one kind of usage of an object, and it is part of its API, so if the object is instantiated you are already using its API implicitly.

 > Could I make PR that takes addition optional config parameters to prevent that behaviour if it is not necessary?

I would be against allowing working around rules like that.
ProxyManager generates proxies that are as un-opinionated as possible, and I'd like to keep it like that. Try using a custom generator in your project first (if this is critical path for you).

**Comment by Ocramius** [comment]
Note: the problem is that while `__destruct` is usually used just for cleanup tasks, some people may actually design legit API in the destructor, and ProxyManager cannot assume that the consumer has written a sane destructor.

**Comment by malinink** [comment]
Now I catch that!

Custom generator is a good idea! Thanks!

**Comment by Ocramius** [comment]
@malinink note, this is the bit that is interesting for your experimenting: https://github.com/Ocramius/ProxyManager/blob/842a41b73713940352c9589a6e3805fb0c69a29a/src/ProxyManager/ProxyGenerator/LazyLoadingGhostGenerator.php#L85-L87
