### ISSUE TITLE
app < php5.5 are broken since 1.0.2

### ISSUE THREAD

**Issue by ProPheT777** [Ocramius/ProxyManager#259]
Hey, 

All php application =< php5.5 are broken via zend code :(

cheers

**Comment by ProPheT777** [comment]
Same with zend code deps, need to use composer replace to fix it.

**Comment by Ocramius** [comment]
Can you clarify? What was broken? All php versions were tested carefully previous to releasing a patch version.

**Comment by ProPheT777** [comment]
Nevermind, problems come from environment/platform when composer was run, he picked the highest dependency wich was wrong.

**Comment by Ocramius** [comment]
Thanks for clarifying!
