### ISSUE TITLE
PHP Fatal error:  Class 'Zend\Stdlib\ArrayObject' not found in vendor/zendframework/zend-code/src/Generator/ValueGenerator.php on line 89

### ISSUE THREAD

**Issue by narozhniyy** [Ocramius/ProxyManager#260]
Hi all. Have issue with Ocramius/ProxyManager, get package from composer and in zendframework/zend-code/src/Generator/ValueGenerator.php used Zend\Stdlib\ArrayObject; But this class not available, and I have PHP Error.
Maybe need change  use  Zend\Stdlib\ArrayObjec  on  use ArrayObject and all going work.

**Comment by malukenho** [comment]
Hello @narozhniyy,

Can you provide me the version of proxy manager that you're using? I tried to reproduce the problem using `"ocramius/proxy-manager": "1.0.*"` version, and all works fine.

Do you already try to reinstall the library?
`composer remove ocramius/proxy-manager` and then `composer require ocramius/proxy-manager:1.0.*`

**Comment by narozhniyy** [comment]
HI @malukenho, 
I used equire ocramius/proxy-manager:1.0.*, but now update to "ocramius/proxy-manager": "1.0.*" and nothing is change.
@malukenho  can you look into vendor/zendframework/zend-code/src/Generator/ValueGenerator.php, ArrayObject() - Undefined  Class?

http://i.imgur.com/vDBiXLA.png
http://i.imgur.com/eKwJMF3.png

ArrayObject describe as Underfined Class

**Comment by malukenho** [comment]
It seems like something is wrong with your network or installation process. As I said, all is working fine, even on `~0.5` version.

Can you check if you have `vendor/zendframework/zend-stdlib` folder?

**Comment by narozhniyy** [comment]
No, I doesn't have this folder only  ``` zend-code ``` and ``` zend-eventmanager ```

**Comment by malukenho** [comment]
Yeah. As I suspected, you're having trouble with installation. Try run `composer update` and see what happens.

**Comment by narozhniyy** [comment]
I did it many times today, removed ```vendor``` folder and did it again

http://i.imgur.com/AMoiAs2.png

After update ```zend-stdlib``` folder doesn't exists

**Comment by malukenho** [comment]
@narozhniyy I finally understand what is happening. `"minimum-stability": "dev"` is breaking the operation of the library. Ouch!

**Comment by narozhniyy** [comment]
@malukenho what i should to do? change "minimum-stability" value.

**Comment by malukenho** [comment]
@narozhniyy Probably yes, or you can add `"zendframework/zend-stdlib": "*@STABLE"` to your composer file, as a temporary solution until we fix this.

**Comment by narozhniyy** [comment]
@malukenho, yes that's help me, now all work and folders are exists. @malukenho thanks

**Comment by malukenho** [comment]
@narozhniyy you're welcome. I'll notify you when this is fixed.

**Comment by Ocramius** [comment]
This needs to be reported on [zendframework/zend-code](https://github.com/zendframework/zend-code), @narozhniyy. Please open an issue there and link it here for reference :-)

**Comment by nicolas-grekas** [comment]
here is the issue:
- ocramius/proxy-manager requires zendframework/zend-code `^2.2.5`
- zendframework/zend-code requires zendframework/zend-eventmanager `^2.6|^3.0` and
- zendframework/zend-code also requires zendframework/zend-stdlib but this is implicit, not explicit
- zendframework/zend-eventmanager 2.x (branch develop) **does** "require" zendframework/zend-stdlib
- zendframework/zend-eventmanager 3.0 (branch develop) **does not** "require" zendframework/zend-stdlib

Which means that either:
- zendframework/zend-code needs to explicitly require zend-stdlib
- or zendframework/zend-eventmanager 3.0 needs to explicitly require zend-stdlib
- or ocramius/proxy-manager needs to explicitely require zend-stdlib
- or ocramius/proxy-manager needs to "conflict" with zendframework/zend-eventmanager 3.0

I think the best is for zendframework/zend-code 2 to explicitly require zend-stdlib (or to stop accepting eventmanager 3, but this is not a strategic move for zf3 :) )

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/symfony/pull/16553 for a temporary workaround on Symfony

**Comment by Ocramius** [comment]
Also to be followed: zendframework/zend-code#23

**Comment by Maks3w** [comment]
#23 has been released in zend-stdlib: 2.5.3 This can be closed.

**Comment by malukenho** [comment]
@Maks3w Thanks you so much!
