### ISSUE TITLE
Proxy __destruct unnecessary initializer

### ISSUE THREAD

**Issue by mcfedr** [Ocramius/ProxyManager#262]
I know this issue was discussed as  #258

I am having the same issue as the original poster, but I am using Symfony, at the end of a request, the __destruct method being called on my lazy services.

I know you said you don't want to have specific code for certain functions, but you do already have, I think all, the other magic methods covered in special ways.

I don't think It makes sense to never call the `__destruct` method, but to not call it if the proxied value has never been initialised.

For the `LazyLoadingValueHolder` that Symfony uses this means that the `__destruct` is the same as other methods, but it doesn't call the initializer.

**Comment by Ocramius** [comment]
> I am having the same issue as the original poster, but I am using Symfony, at the end of a request, the __destruct method being called on my lazy services.

The problem is that this library has to stay agnostic about the use-cases of your objects. People do depend on `__destruct` for the wildest things, and therefore it should be called regardless of the use-case, when defined.

It should initialize the objects in order to guarantee proper functioning of the `__destruct` internals.

**Comment by mcfedr** [comment]
Surely if the wrapped value hasn't even been initialised `__destruct` it makes no sense to call it. I understand that there might be weird use cases for `__destruct` but should that be at the expense of a normal use case?

I am trying to proxy `Redis` as a lazy service in Symfony. But because `__destruct` is called at the end of each request I basically going to have to make my own proxy inside the proxy.

**Comment by Ocramius** [comment]
> Surely if the wrapped value hasn't even been initialised `__destruct` it makes no sense to call it. 

This is opinionated. While I believe the following use-case to be stupid, I've seen it used in the field:

```php
class MyMail
{
    // ... stuff
    public function __destruct()
    {
        if (! $this->wasSent()) {
            $this->send();
        }
    }
}
```

This library *CANNOT* take opinionated approaches: if you need to take an opinionated direction, then please implement your own proxy generator starting from changing [this line](https://github.com/Ocramius/ProxyManager/blob/c27607f1c67058e73a3b79dad3784931b26de59a/src/ProxyManager/ProxyGenerator/LazyLoadingValueHolderGenerator.php#L94).

**Comment by Ocramius** [comment]
> But because `__destruct` is called at the end of each request I basically going to have to make my own proxy inside the proxy. 

Maybe you could link me to the specific class you are trying to proxy, and we can find an alternate approach?

**Comment by mcfedr** [comment]
I am trying to use [Redis](https://github.com/phpredis/phpredis#class-redis) as a Symfony service. I want it to be lazy because not every request needs to connect to it.

**Comment by Ocramius** [comment]
@mcfedr is the connection enstabilished at `__construct`?

**Comment by mcfedr** [comment]
Unfortunately not, my service looks like this:

    project.redis:
        class: Redis
        calls:
            - [ connect, ["%redis_host%"]]
            - [ setOption, ["%redis_prefix_option%", "%resque_prefix%"]]

**Comment by Ocramius** [comment]
If the connection is not enstabilished at `__construct`, then having the service being created each time shouldn't be an issue.

**Comment by mcfedr** [comment]
But the closure that Symfony makes and gives to the Proxy calls `__construct` and `connect`.

**Comment by Ocramius** [comment]
> But the closure that Symfony makes and gives to the Proxy calls `__construct` and `connect`.

That is a completely different story then :-) Why doesn't the `connect` happen implicitly when calling any method on the adapter? Sounds like some responsibilities are kinda messed up there...
