### ISSUE TITLE
Broken links in footer http://ocramius.github.io/ProxyManager/

### ISSUE THREAD

**Issue by holtkamp** [Ocramius/ProxyManager#263]
It seems 3 out of 5 links are broken:

- https://ocramius.github.io/ProxyManager/STABILITY.html
- https://ocramius.github.io/ProxyManager/UPGRADE.html
- https://ocramius.github.io/ProxyManager/CONTRIBUTING.html

**Comment by Ocramius** [comment]
@holtkamp fixed, thanks!
