### ISSUE TITLE
Duplicate semicolons generated

### ISSUE THREAD

**Issue by holtkamp** [Ocramius/ProxyManager#264]
When looking at some generated code when used in combination with [PHP-DI](https://github.com/PHP-DI/PHP-DI), the proxy classes contain snippets like:

```php
            return isset($targetObject->$name);;
            return;
```

```php
            unset($targetObject->$name);;
            return;
```

Note the duplicate semicolons, which seems to be caused by [this line](https://github.com/Ocramius/ProxyManager/blob/842a41b73713940352c9589a6e3805fb0c69a29a/src/ProxyManager/ProxyGenerator/Util/PublicScopeSimulator.php#L74)

**Comment by Ocramius** [comment]
@holtkamp fixed, thanks!
