### ISSUE TITLE
Testcase failures with PHP 7.0.2 and php-proxy-manager 1.0.2

### ISSUE THREAD

**Issue by nacc** [Ocramius/ProxyManager#286]
I'm trying to work towards PHP 7 support in Ubuntu 16.04 and the current version of the proxy-manager packge is 1.0.2. As the phpunit tests fail, I'm unable to build the package successfully.

Note, I tried to update to 2.0.0-beta2 and there were many more failures. I can provide those logs as well, if desired.

Attaching the 1.0.2 logs.
[php-proxy-manager.errors.txt](https://github.com/Ocramius/ProxyManager/files/108580/php-proxy-manager.errors.txt)

**Comment by nacc** [comment]
The 2.0.0-beta2 failures, in case PHP7 support is only intended with that branch.
[php-proxy-manager_2.0.0_beta2.errors.txt](https://github.com/Ocramius/ProxyManager/files/108594/php-proxy-manager_2.0.0_beta2.errors.txt)

Note that some large percentage of these seem due to php-zend-code not defining setReturnType() or setReturnsReference.

After looking into a bit more, it seems this might be due to having an older php-zend-code in Debian/Ubuntu. Updating to 3.0.1 from Debian/experimental reduced the issues to not having PackageVersions packaged for Debian, it seems.

**Comment by nacc** [comment]
Per the page at https://www.versioneye.com/php/ocramius:proxy-manager/1.0.2, though I should be able to use 1.0.2 with PHP7, yes?

**Comment by Ocramius** [comment]
I just checked as well:

 * 2.0.0 works smoothly (must run a composer update, but no failures)
 * 1.0.2 reports multiple failures with re-binding logic, although it's only in fatal prevention emulation

ProxyManager 2.0.0 is due tomorrow (that's when I plan to release it), and [we are past the bugfix-support schedule for 1.0.0 by at least a month](https://github.com/Ocramius/ProxyManager/blob/1.0.2/STABILITY.md#10x). Given that the failures reported are indeed just minor cases (emulating fatal errors: your app would crash anyway, except that the error messages don't match), I don't think it's worth fixing those. I'd move forward and release 2.0.0 tomorrow.

Please run a clean composer installation of the latest `2.0.0-BETA2` and check the error messages again, and please do not rely on any globally installed packages for this.

**Comment by nacc** [comment]
Thanks for the pointers. I will work with Debian to get the newer version of php-proxy-manager packaged, which appears to also require a new dependency package (php-package-versions, i.e.). To be clear, I work for Canonical and am doing this packaging quite intentionally. So getting it to work with composer is a good test of how it should look, but I also am very interested in the packaged versions building from source (and passing phpunit tests).

**Comment by Ocramius** [comment]
@nacc just so we don't cause any false-expectations: I am not going to fix/merge fixes for these failures related to 1.x + PHP 7.0.0. They can eventually be marked as XFAIL in the debian package, if the tests are still relevant there. I went through all this fixing already once for 2.x.

2.0.0 will have full PHP 7.0.0 support and can be used pretty much in the same way, except for [some BC breaks](https://github.com/Ocramius/ProxyManager/blob/2.0.0-BETA3/UPGRADE.md#200)
