### ISSUE TITLE
Setting value on proxy via ReflectionProperty causes an error.

### ISSUE THREAD

**Issue by bendavies** [Ocramius/ProxyManager#298]
Hi there,

I have a lazy service.

ProxyManger generates a `__set` method (via `ProxyManager\ProxyGenerator\UtilPublicScopeSimulator`) that looks like:
```
    public function __set($name, $value)
    {
        $this->initializer56d6e5ca17346071728280 && $this->initializer56d6e5ca17346071728280->__invoke($this->valueHolder56d6e5ca17340889958830, $this, '__set', array('name' => $name, 'value' => $value), $this->initializer56d6e5ca17346071728280);
        $realInstanceReflection = new \ReflectionClass(get_parent_class($this));
        if (! $realInstanceReflection->hasProperty($name)) {
            $targetObject = $this->valueHolder56d6e5ca17340889958830;
            return $targetObject->$name = $value;
            return;
        }
        $targetObject = $this->valueHolder56d6e5ca17340889958830;
        $accessor = function & () use ($targetObject, $name, $value) {
            return $targetObject->$name = $value;
        };
            $backtrace = debug_backtrace(true);
            $scopeObject = isset($backtrace[1]['object']) ? $backtrace[1]['object'] : new \ProxyManager\Stub\EmptyClassStub();
            $accessor = $accessor->bindTo($scopeObject, get_class($scopeObject));
        $returnValue = & $accessor();
        return $returnValue;
    }
```

If you then set a value via `ReflectionProperty` on this proxy, you will receive an error:
> Cannot bind closure to scope of internal class ReflectionProperty

on the `bindTo` call.

Let me know if you need anything else?

**Comment by Ocramius** [comment]
Argh, php limitations.

Could you write an example, following the ones in https://github.com/Ocramius/ProxyManager/tree/master/tests/language-feature-scripts ?

**Comment by bendavies** [comment]
yep, sure. will do

**Comment by bendavies** [comment]
here you go
```
--TEST--
Verifies that generated access interceptors allow protected property write via Reflection
--FILE--
<?php

require_once __DIR__ . '/init.php';

class Kitchen
{
    protected $sweets;
}

$factory = new \ProxyManager\Factory\AccessInterceptorValueHolderFactory($configuration);

$proxy = $factory->createProxy(new Kitchen());

$reflO = new \ReflectionObject($proxy);
$reflP = $reflO->getProperty('sweets');

$reflP->setAccessible(true);
$reflP->setValue($proxy, 'stolen');

echo $proxy->sweets;
?>
--EXPECTF--
stolen

```

**Comment by Ocramius** [comment]
Hmm... Is this ProxyManager 2.x? I can't seem to be able to generate a proxy with the same signature...

Could you send a PR with just that file, so we see what @travis-ci's opinion on this is?

**Comment by bendavies** [comment]
Yep, 2.x on php 7.0.3.
I'm away from real internet for a few days but will submit the PR when back connected.

**Comment by bendavies** [comment]
Actually it's 3.x. I didn't realise your master branch was 3.x now.

**Comment by Ocramius** [comment]
> I'm away from real internet for a few days but will submit the PR when back connected.

Thanks!

Also, I think I did code workarounds for reflection-based access in the ghost objects, but not in the value holders. Will have to check...

**Comment by bendavies** [comment]
@Ocramius there you go

**Comment by Ocramius** [comment]
Closing here, since #299 provides the actual failing test case.
