### ISSUE TITLE
Intercept all method calls?

### ISSUE THREAD

**Issue by mnapoli** [Ocramius/ProxyManager#302]
`AccessInterceptorInterface` only allows to intercept specific methods (`setMethodPrefixInterceptor()`  requires a method name). Is there a way to intercept all method calls to the proxy? I couldn't find anything after searching a bit, I hope I didn't miss something obvious.

**Comment by Ocramius** [comment]
This is a duplicate of #236

**Comment by mnapoli** [comment]
:+1:
