### ISSUE TITLE
Undefined method setxtendedClass on class ProxyManager\Generator\ClassGenerator

### ISSUE THREAD

**Issue by devckonem** [Ocramius/ProxyManager#303]
Hello, 

I have an issue on version 1.0.2, I'm trying to use your ProxyManager to make ghost objects for a project of mine and I'm having trouble using it because of this:

[Symfony\Component\Debug\Exception\UndefinedMethodException]                                                     
  Attempted to call an undefined method named "setxtendedClass" of class "ProxyManager\Generator\ClassGenerator".  
  Did you mean to call e.g. "getExtendedClass" or "setExtendedClass"?

If I modify the code and use setExtendedClass instead of setxtendedClass it wil work.

Thanks.

**Comment by Ocramius** [comment]
Can't seem to find the offending code: https://github.com/Ocramius/ProxyManager/blob/57e9272ec0e8deccf09421596e0e2252df440e11/src/ProxyManager/Generator/ClassGenerator.php#L34-L41

Please check that the file wasn't modified by accident locally (remove the `vendor/ocramius/proxy-manager` dir and re-run `composer install`).

**Comment by devckonem** [comment]
Strange because I didn't alter the files locally just installed it with composer, now it works.

Thanks.

**Comment by Ocramius** [comment]
@devckonem thanks for checking!
