### ISSUE TITLE
Documentation on version 1.*

### ISSUE THREAD

**Issue by devckonem** [Ocramius/ProxyManager#304]
Hello,

Can you make different documentations for the different versions of the ProxyManager? Because in version 1.* i see that the LazyLoadingGhostFactory method createFactory accepts only 2 params and in the current doc i suppose version 2.* it accepts 3 params.

Thanks.

**Comment by Ocramius** [comment]
Docs are versioned inside the repo: 

 * https://github.com/Ocramius/ProxyManager/tree/2.0.1/docs
 * https://github.com/Ocramius/ProxyManager/tree/1.0.2/docs

**Comment by devckonem** [comment]
Ok, thanks for the docs, but how can I use the "skippedProperties" from https://github.com/Ocramius/ProxyManager/blob/2.0.1/docs/lazy-loading-ghost-object.md#skipping-properties-properties-that-should-not-be-initialized in version 1.0.2?

**Comment by Ocramius** [comment]
No, [skipping properties was only implemented in 2.0.0](https://github.com/Ocramius/ProxyManager/blob/2.0.1/CHANGELOG.md#skipping-lazy-loaded-properties-in-generated-proxies), as it required massive internal changes, sorry.

**Comment by devckonem** [comment]
My case is a data mapper and I don't want the loading to be triggered when the user calls Object->getId(), because it will be set by default. Is there a way around this?

**Comment by devckonem** [comment]
The answer is yes you can do it with Reflection:

```php
$instance = $factory->createProxy(MyClass::class, $initializer);
$idRef = new \ReflectionProperty(MyClass::class, 'id');
$idRef->setAccessible(true);
$idRef->setValue($instance, 1);
```

And then if you access another method on class MyClass then it will trigger the $initializer.

**Comment by Ocramius** [comment]
That will break in two cases:
 1. if the property is public
 2. if you upgrade to v2 at some point

**Comment by Ocramius** [comment]
I warmly suggest just upgrading to v2 btw. Any reason you are locked in v1?

**Comment by devckonem** [comment]
You have required php 7 for version 2.

PS: Also I can refine the previous code and it will break only if I upgrade to v2.
```php
/**
 * @param   string  $className
 * @param   object  $object
 * @param   array   $propertyValues
 *
 * @return  void
 * @throws  \ReflectionException
 */
public function skipProperties($className, &$object, array $propertyValues)
{
    foreach ($propertyValues as $property => $value) {
        $ref = new \ReflectionProperty($className, $property);
        if (!$ref->isPublic()) {
            $ref->setAccessible(true);
        }
        $ref->setValue($object, $value);
    }
}
```

**Comment by Ocramius** [comment]
@devckonem no, public properties will trigger lazy-loading regardless. You will need something like this: https://github.com/doctrine/common/blob/773c56e51fc26ae07a47146fae31b320dd6cada3/lib/Doctrine/Common/Reflection/RuntimePublicReflectionProperty.php

**Comment by devckonem** [comment]
I've just tested that scenario and it doesn't trigger lazy-loading if the attribute is public. I've put a var_dump() in the $initializer Closure to see when it is called.

**Comment by Ocramius** [comment]
Alright then :)

Still, consider jumping to v2 when possible.

Closing here, as the question seems to be answered.
