### ISSUE TITLE
variadic parameters

### ISSUE THREAD

**Issue by hboomsma** [Ocramius/ProxyManager#307]
In PHP 5.6 variadic function and method parameters were added. These are currently not supported. Also an one of the issues in #210 HHVM Compatibility.

**Comment by Ocramius** [comment]
These are already supported: https://github.com/Ocramius/ProxyManager/blob/6e15877fc03cc211ce798d497a21208a44f7b726/tests/ProxyManagerTest/Functional/MultipleProxyGenerationTest.php#L130-L131

**Comment by hboomsma** [comment]
Thnx!
I sent a full request to Symfony to update the documentation on lazy services to require version 2 instead of 1.

**Comment by hboomsma** [comment]
Problem persists however for PHP 5.6! There version 2 can not be installed.

**Comment by malukenho** [comment]
Could you provide us some tests reproducing the bug? @hboomsma

**Comment by Ocramius** [comment]
> There version 2 can not be installed.

I don't support 1.x anymore (besides security fixes): upgrading to PHP 7.0 is required here.

**Comment by tdtm** [comment]
@Ocramius: I've encountered the issue (I know, 2019, PHP 5.6 🙄). Would you accept a PR for it?

**Comment by Ocramius** [comment]
Nope, please upgrade
