### ISSUE TITLE
Generated code has $this as a parameter which breaks in php 7.1.

### ISSUE THREAD

**Issue by darianbr** [Ocramius/ProxyManager#309]
The proxy generator is generating code that has `$this` as the parameter:
```
\Closure::bind(function (\Doctrine\DBAL\Connection $this) {
```

In php 7.1.0-dev, `$this` cannot be used as a parameter and the follow error is being generated:
```
[RuntimeException]                                                           
  Error Output: PHP Fatal error:  Cannot use $this as parameter in /home/trav  
  is/build/xyz/abc/vendor/ocramius/proxy-manager/src/ProxyManager/Ge  
  neratorStrategy/EvaluatingGeneratorStrategy.php(68) : eval()'d code on line  
   640    
```

**Comment by malukenho** [comment]
@darianbr we actually have a workaround in the #308 PR

**Comment by darianbr** [comment]
@malukenho I have tested my code against the hotfix in the #308 PR and can confirm that it fixes this issue.
