### ISSUE TITLE
Add skippedProperties to other proxies than the GhostObject

### ISSUE THREAD

**Issue by Jelle-S** [Ocramius/ProxyManager#311]
For example for the Remote Object:

Some api's return a list of items with only limited data (for example $remoteObj->name and $remoteObj->id). We could create a proxy object that already contains that data. As long as no other data is required, no call to the remote is made. Once other data is required  ($remoteObj->email) we make the call to fetch the rest of the data.

So for example:
example.com/user returns:

```
[
  {
    id: 1,
    name: 'user1'
  },
  {
    id: 2,
    name: 'user2'
  }
  ...
]
```

and example.com/user/1 returns:

```
{
  id: 1,
  name: 'user1',
  email: 'user1@example.com',
  picture: 'http://www.example.com/path/to/picture.jpg',
  signature: 'My signature'
}
```

**Comment by Ocramius** [comment]
Note to self: dug deeper into the implementation details required for this, and unless we make all proxies actual ghost objects (safest implementation), I do not think that this particular feature is implementable.

**Comment by Ocramius** [comment]
Looking back at this, I think this is "caching" that should be handled entirely by the application that is controlling ProxyManager.

In practice, this means that a `__call` should be intercepted.

In the test suite:

https://github.com/Ocramius/ProxyManager/blob/f65ae0f9dcbdd9d6ad3abb721a9e09c3d7d868a4/tests/ProxyManagerTest/Functional/RemoteObjectFunctionalTest.php#L135-L150

This means that the RPC adapter should intercept `__call` and check (on its own) if a remote call is to be performed, or if local cache already contains the value to be used.

Therefore, closing here: this can (and should) be implemented in userland, while the tool should really focus on keeping a very transparent and (albeit already very magic) as-magicless-as-possible implementation of the retrieved proxy.
