### ISSUE TITLE
Symfony Lazy Services don't work with PHP 7.0.7

### ISSUE THREAD

**Issue by Hast** [Ocramius/ProxyManager#316]
PHP 7.0.7 was released today, including [bugfix#71737 (Memory leak in closure with parameter named $this)](https://bugs.php.net/bug.php?id=71737).

Now, all compiled symfony lazy services throw this exception:

`FatalErrorException in appDevDebugProjectContainer.php: Compile Error: Cannot use $this as parameter`

This is the line from the debug container causing the problem: http://joxi.ru/XEA4JEfDYaKemb.jpg

Looks like a critical issue, because we have to either downgrade to 7.0.6 or turn off all lazy services in the project.

Tested with symfony 3.0 branch.

**Comment by Ocramius** [comment]
Already handled in https://github.com/Ocramius/ProxyManager/pull/308
