### ISSUE TITLE
Generated code doesn't work with PHP 7.0.7

### ISSUE THREAD

**Issue by soukicz** [Ocramius/ProxyManager#319]
PHP 7.0.7 added new restriction on closures that arguments cannot be named "$this". Proxy manager doesn't check for that and generated code causes fatal error. 

I have managed to track it down to this code in symfony container. It is generated from *ProxyManager\ProxyGenerator\Util\UnsetPropertiesGenerator->generateUnsetClassPrivatePropertiesBlock()*

Unfortunately I don't understand proxy-manager or symfony internals very well to create test case. 

I think that closure argument probably should have fixed name to avoid this issue (it is used only once inside closure anyway).

```php
// /var/www/project/var/cache/prod/appProdProjectContainer.php

public function __construct(\Symfony\Component\Serializer\SerializerInterface $serializer)
    {
        static $reflection;
        if (! $this->valueHolder574a480406241280270337) {
            $reflection = $reflection ?: new \ReflectionClass('FOS\\RestBundle\\Serializer\\SymfonySerializerAdapter');
            $this->valueHolder574a480406241280270337 = $reflection->newInstanceWithoutConstructor();
        \Closure::bind(function (\FOS\RestBundle\Serializer\SymfonySerializerAdapter $this) {
            unset($this->serializer);
        }, $this, 'FOS\\RestBundle\\Serializer\\SymfonySerializerAdapter')->__invoke($this);
        }
        $this->valueHolder574a480406241280270337->__construct($serializer);
    }


public function __wakeup()
    {
        \Closure::bind(function (\FOS\RestBundle\Serializer\SymfonySerializerAdapter $this) {
            unset($this->serializer);
        }, $this, 'FOS\\RestBundle\\Serializer\\SymfonySerializerAdapter')->__invoke($this);
    }
```

Relevant PHP issue: https://bugs.php.net/bug.php?id=71737

**Comment by soukicz** [comment]
Oh, my bad. I just noticed in release notes, that PHP 7.0.7 is not yet supported.

**Comment by Ocramius** [comment]
Actually, it is supported. I released https://github.com/Ocramius/ProxyManager/releases/tag/2.0.2 a couple of days ago, and it includes 7.0.7 support.

You are probably running on 2.0.1, please upgrade.

**Comment by soukicz** [comment]
Thank you for your help!

I just discovered my mistake - I am running different minor PHP versions on *dev* and *prod*. I have generated composer.lock on dev with PHP 7.0.4 and it didn't install 2.0.2 version. That's what happens when I try to debug something at 4 AM :)

**Comment by Ocramius** [comment]
Heh, I'm debugging 7.1.0-DEV at 4 AM... fun times :-\
