### ISSUE TITLE
Unsupported declare 'strict_types' in /vendor/ocramius/proxy-manager/src/ProxyManager/Configuration.php

### ISSUE THREAD

**Issue by napestershine** [Ocramius/ProxyManager#328]
Hi

I am getting following error in my symfony project about Ocramius/ProxyManager.

Warning: Unsupported declare 'strict_types' in project/vendor/ocramius/proxy-manager/src/ProxyManager/Configuration.php on line 19

Parse error: syntax error, unexpected ':', expecting ';' or '{' in project/vendor/ocramius/proxy-manager/src/ProxyManager/Configuration.php on line 97

How can I resolve it?

Thanks

**Comment by malukenho** [comment]
@napestershine which one is your php version?

**Comment by napestershine** [comment]
Hi @malukenho 

My PHP version is PHP Version 5.6.20

Thanks for support

**Comment by malukenho** [comment]
@napestershine you need a compatible php version, which is `7.0.0 - 7.0.5 || ^7.0.7`.

You can update your php version or downgrade the ProxyManager.

yw!

**Comment by napestershine** [comment]
@malukenho  how can i downgrade proxy manager version?

**Comment by malukenho** [comment]
`composer require ocramius/proxy-manager`

@napestershine

**Comment by napestershine** [comment]
@malukenho  Thanks I will try it

**Comment by napestershine** [comment]
@malukenho  which version of Ocraminus Proxy-manager support php5.6.20?

**Comment by Ocramius** [comment]
1.0.* supports ancient 5.* PHP versions.

**Comment by nachomozo** [comment]
I have exactly de same issue with ocramius/proxy-manager 2.0.3 and PHP 7.0.10

**Comment by jaoued** [comment]
Hi,

I have the same issue and i use `PHP 7.1.1`

Regards

**Comment by Ocramius** [comment]
@jaoued check if it's both for CLI and your web setup. This code is tested against PHP 7.1.1, so you are evidently not running PHP 7.1 in the target environment.

**Comment by jaoued** [comment]
I've checked in terminal: 

```zsh
> php -v
PHP 7.1.1 (cli) (built: Jan 21 2017 13:36:56) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
```

**Comment by Ocramius** [comment]
That's your command line, which isn't what libapache2modphp7 uses, nor what fastcgi uses.

**Comment by jaoued** [comment]
Ok, so how i can check this? I use Nginx instead of Apache:

```
> php-fpm -v
PHP 7.1.1 (fpm-fcgi) (built: Jan 21 2017 13:37:00)
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
```

**Comment by Ocramius** [comment]
Put a `phpinfo()` in your project, then check it from there.

**Comment by jaoued** [comment]
<img width="959" alt="general_information_php7-1-1" src="https://cloud.githubusercontent.com/assets/2301050/22620956/5980f026-eb18-11e6-80d2-e31497b25ad1.png">


As you can see, there is the same version here :/

**Comment by Ocramius** [comment]
Can you put that `phpinfo()` exactly where the strict types declaration is (and comment that one out instead)?

As said before, I really really really am confident that your system is simply not running PHP 7.1.* there.

**Comment by tfe2012** [comment]
I have now similar error on php71 version

**Comment by Ocramius** [comment]
As said above: check the php version running the actual script. CLI != CGI
!= mod_PHP

**Comment by indapublic** [comment]
Have same error 
OSX 10.12.5
PHP installed by brew
php -v
PHP 7.1.5 (cli) (built: May 13 2017 13:30:32) ( NTS )
phpinfo: https://dl.dropboxusercontent.com/spa/hbn3pdf9anaiovl/wy_1j1yy.png

**Comment by Ocramius** [comment]
Put a `phpinfo()` in the file that causes the issue, then continue checking from there: you are 99.9% running php 5.

**Comment by indapublic** [comment]
@Ocramius Thanks for reply. Page shows PHP7.1, but GrumpPHP shows message it using PHP5.6, yes.

**Comment by sunyinggang** [comment]
> `phpinfo()`在导致问题的文件中放入一个，然后从那里继续检查：你是99.9％运行php 5。
Check out the php used is 5.6.6,but i don't know this problem,how to change 7.1??

**Comment by sunyinggang** [comment]
> @Ocramius Thanks for reply. Page shows PHP7.1, but GrumpPHP shows message it using PHP5.6, yes.

then?you find the problem,but it didn't solve. How to change 7.1??

**Comment by Ocramius** [comment]
Please simply make sure that all your PHP installations are up to date: this project simply has a dependency to the newest PHP version, and is not really responsible for how you install PHP on your machines.
