### ISSUE TITLE
Ghost object - Missing argument

### ISSUE THREAD

**Issue by elymatos** [Ocramius/ProxyManager#330]
Hello,
I'm getting
[Code] 2 [Error] Missing argument 5 for MBusinessModel::{closure}()
when I try to use a GhostObject (MBusiness model is my class). I cut/paste the example from site, so I don't know about this argument 5.
Thanks,
Ely

**Comment by Ocramius** [comment]
Seems like you have too many arguments in your closure? Can you gist your
code please?

**Comment by elymatos** [comment]
Hello,
it seems that generated code is not passing by the fifth parameter (properties):
https://gist.github.com/elymatos/dbb97c21ead871ea17ad7ba0a48f9e02

I just commented out the fifth parameter in my code.

Btw, I'm using GhostObject to lazy initialization on a small ORM project. I have a class to Model (no persistence) and a class for Map (with persistence). The idea is to call Map methods related to associations, to get data from database. As I can have many such methods in the class, what I'm doing is not setting $initializer to null, so the closure is called many times and I test for the called method. Is this a possible use? Or is it a wrong way for ghostobject?
Thanks for your time, attention and work,
Ely

**Comment by Ocramius** [comment]
> Hello,
 > it seems that generated code is not passing by the fifth parameter (properties):
https://gist.github.com/elymatos/dbb97c21ead871ea17ad7ba0a48f9e02
 > 
 > I just commented out the fifth parameter in my code.

Can you please gist the entire proxy, the class that it originates from, the initializer closure and the creation logic (the logic that calls the factory, etc)?

 > As I can have many such methods in the class, what I'm doing is not setting $initializer to null, so the closure is called many times and I test for the called method. Is this a possible use? Or is it a wrong way for ghostobject?

It is possible, but your internal state will be reset to default property values at each initialization cycle, so you will have to maintain the values somewhere, I fear.

**Comment by Ocramius** [comment]
The code that you linked doesn't seem to come from a ghost object, but from a lazy loading value holder.

I opened #334 to prevent this kind of failure in future (simple with anonymous classes).

Closing this one as invalid.
