### ISSUE TITLE
PHP 7 update

### ISSUE THREAD

**Issue by fcpauldiaz** [Ocramius/ProxyManager#335]
Please update this bundle to be compatible with php 7.0.9 or 7.0.10. It is breaking my apps

**Comment by Ocramius** [comment]
@fcpauldiaz this library runs with 7.0.9 and 7.0.10? What bugs are you encountering?

**Comment by fcpauldiaz** [comment]
I don't have any bugs I just can't install it because of this it is limited to php 7.0.7 in the composer 
https://github.com/Ocramius/ProxyManager/blob/master/composer.json#L22

**Comment by malukenho** [comment]
@fcpauldiaz It isn't limited to `7.0.7` https://getcomposer.org/doc/articles/versions.md#caret

**Comment by Ocramius** [comment]
That simply excludes 7.0.6 from the compatibility, since 7.0.6 included a [quite bad bug](https://bugs.php.net/bug.php?id=72174) that was fixed in PHP [7.0.7](https://bugs.php.net/bug.php?id=72174).
