### ISSUE TITLE
Object-Parameter with null as default

### ISSUE THREAD

**Issue by digilist** [Ocramius/ProxyManager#337]
Consider the following code:

```php

class Foo {
    public function doSomething(\stdClass $a = null, $b) {
    }
}

$factory = new \ProxyManager\Factory\LazyLoadingValueHolderFactory();
$proxy = $factory->createProxy(
    Foo::class,
    function (& $wrappedObject, $proxy, $method, $parameters, & $initializer) {
        $wrappedObject = new Foo(); // instantiation logic here
        $initializer = null; // turning off further lazy initialization
    }
);


$proxy->doSomething(null, 'hi');
```

Executing the code fails with the following message:
> PHP Fatal error:  Uncaught TypeError: Argument 1 passed to ProxyManagerGeneratedProxy\__PM__\Foo\Generated8c05591d466b1fbc8b27e31e8bbeac21::doSomething() must be an instance of stdClass, null given, called in [...]

The function in the proxy is generated with the following code:
```php
public function doSomething(\stdClass $a, $b)
{
    $this->initializer57ebd2a2dfdcf678896500 && $this->initializer57ebd2a2dfdcf678896500->__invoke($this->valueHolder57ebd2a2dfd75078219296, $this, 'doSomething', array('a' => $a, 'b' => $b), $this->initializer57ebd2a2dfdcf678896500);

    return $this->valueHolder57ebd2a2dfd75078219296->doSomething($a, $b);
}
```

It looks like the parameter's default value (null) is skipped, if the parameter is not optional. This prevents me from passing null to the function instead of an object.

This happens with version 1 and 2.

**Comment by digilist** [comment]
Sorry, I dug deeper into the problem and it is actually a problem within zend-code. I will open a bug report there.

**Comment by Ocramius** [comment]
Was moved to zendframework/zend-code#95
