### ISSUE TITLE
Unable to serialize proxy factory, when using FileWriterGeneratorStrategy as cache

### ISSUE THREAD

**Issue by DaGhostman** [Ocramius/ProxyManager#340]
At the moment, the `FileWriterGeneratorStrategy` sets and resets the error handler to an empty closure. The problem arises, when trying to serialize a proxy factory, which uses it as a caching mechanism. 

The serialization fails with `Uncaught Exception: Serialization of 'Closure' is not allowed`

**Comment by Ocramius** [comment]
See https://github.com/Ocramius/ProxyManager/pull/341#issuecomment-252789509 - closing as `invalid`
