### ISSUE TITLE
Support interface-bound proxies

### ISSUE THREAD

**Issue by theofidry** [Ocramius/ProxyManager#347]
Follow up of https://github.com/theofidry/AliceDataFixtures/issues/16. When proxying a final class, you get right away an error like "class X cannot be proxied". In some regard, it does makes sense as a final class is not meant to be inherited. But a final class may inherit from another class and/or implement interfaces, in which case it would be nice to have a proxy that can actually be used for it. The only failing case that I would find reasonable (I'm sure we could eventually get around it but I would prefer to leave it to you if it actually makes sense or not), is when you typehint a final class: you would expect a final class instance.

Related issues:

- https://github.com/theofidry/AliceDataFixtures/issues/16
- https://github.com/symfony/symfony/issues/20392

**Comment by theofidry** [comment]
Another related issue: https://github.com/symfony/symfony/issues/20656.

After those discussion, I think it's fair to reformulate the problem differently and ask if ProxyManager could support interfaces bound proxies besides of concrete implementations.

**Comment by nicolas-grekas** [comment]
The page about [Lazy Loading Value Holder Proxy](https://ocramius.github.io/ProxyManager/docs/lazy-loading-value-holder.html) has a § at the end that tells this is supported. Is this something else?

**Comment by Ocramius** [comment]
As per:

https://github.com/Ocramius/ProxyManager/blob/f65ae0f9dcbdd9d6ad3abb721a9e09c3d7d868a4/src/ProxyManager/Factory/LazyLoadingValueHolderFactory.php#L33-L40

`ocramius/proxy-manager` supports implementing value holder proxies when the wrapped value is an instance of the provided interface.

In `symfony/proxy-manager-bridge`, this is done by providing a "proxified class" in the definition:

https://github.com/symfony/symfony/blob/44e98dba0d33f6303f2c1d077ae08d4ac2254649/src/Symfony/Bridge/ProxyManager/LazyProxy/Instantiator/RuntimeInstantiator.php#L41-L53

It may be necessary to define a new parameter in the container definition, to do so, but that needs to happen in the DIC declaration.
