### ISSUE TITLE
Parametrized proxies

### ISSUE THREAD

**Issue by evpav** [Ocramius/ProxyManager#352]
Hello, I'm trying to create parametrized proxies like so:
```php
function getClassProxy($param) {
    return (new LazyLoadingValueHolderFactory)->createProxy(
        'Class',
        function (
            &$wrappedObject,
            LazyLoadingInterface $proxy,
            $method,
            array $parameters,
            &$initializer
        ) use ($param) {
            $initializer = null;
            $wrappedObject = new Class($param);
            return true;
        }
    );
}

$proxy1 = getClassProxy('foo');
$proxy2 = getClassProxy('bar');

echo $proxy1->param; // 'bar'
echo $proxy2->param; // 'bar'

```
but end up with the same proxied object. Is it by design or my code is wrong? Is it possible to do this at all? I'm using version 1.0.2, because I cannot use php7 on this particular project.

**Comment by evpav** [comment]
Sorry, my bad, an error in my code was causing this.

**Comment by Ocramius** [comment]
Seems correct to me: what do you mean by "same proxied object"? Check
tests/language-features-test and try writing a .phpt exposing the issue
