### ISSUE TITLE
Uncaught TypeError: Return value of ProxyManager\ProxyGenerator\Assertion\CanProxyAssertion::isNotFinal()

### ISSUE THREAD

**Issue by andreybolonin** [Ocramius/ProxyManager#355]
``Fatal error detected on file "vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/Assertion/CanProxyAssertion.php" at line 72 with message: "Uncaught TypeError: Return value of ProxyManager\ProxyGenerator\Assertion\CanProxyAssertion::isNotFinal() must be an instance of ProxyManager\ProxyGenerator\Assertion\void, none returned in /home/foobar/code/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/Assertion/CanProxyAssertion.php:72
Stack trace:
#0 /home/foobar/code/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/Assertion/CanProxyAssertion.php(54): ProxyManager\ProxyGenerator\Assertion\CanProxyAssertion::isNotFinal(Object(ReflectionClass))
#1 /home/foobar/code/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/LazyLoadingValueHolderGenerator.php(72): ProxyManager\ProxyGenerator\Assertion\CanProxyAssertion::assertClassCanBeProxied(Object(ReflectionClass))
#2 /home/foobar/code/vendor/symfony/symfony/src/Symfony/Bridge/ProxyManager/LazyProxy/PhpDumper/ProxyDumper.php(133): ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator->generate(Object(ReflectionClass), Object(ProxyManager\Generator\ClassGenerator))
#3 "``

**Comment by Ocramius** [comment]
Do **NOT** install composer dependencies without checking for environment compatibility. You are running PHP 7.1 code on PHP 7.0.
