### ISSUE TITLE
Return type error

### ISSUE THREAD

**Issue by avg0043** [Ocramius/ProxyManager#356]
Hi everyone,

I'm getting a return type error in file src\ProxyManager\Configuration.php. The error is the following:

> Warning: Unsupported declare 'strict_types'.
> 
> Parse error: sintax error, unexpected ':', expecting ';' or '{' in Configuration.php on line 97.

And the file code in which resides the problem:

```
declare(strict_types=1);

namespace ProxyManager;

class Configuration
{
public function getProxyAutoloader() : AutoloaderInterface
    {
        return $this->proxyAutoloader
            ?: $this->proxyAutoloader = new Autoloader(
                new FileLocator($this->getProxiesTargetDir()),
                $this->getClassNameInflector()
            );
    }
}
```

Line 97 error corresponds with the method declaration.

Why I'm getting this error if I'm using PHP 7.0.13 and it supports return types method?

Thanks.

**Comment by Ocramius** [comment]
@avg0043 check that your CLI and your http server are running both on > 7.0.0.

**Comment by avg0043** [comment]
Thanks I will check it

**Comment by yellowmamba** [comment]
I can confirm the same issue for PHP 7.0.13-0ubuntu0.16.04.1 on both CLI and PHP-FPM.

**Comment by Ocramius** [comment]
@yellowmamba ProxyManager 2.1.x **REQUIRES PHP 7.1** as per https://github.com/Ocramius/ProxyManager/blob/2.1.0/composer.json

**Comment by yellowmamba** [comment]
Sorry @Ocramius my bad. I was just about to clarify my mistake, I am using 2.0.4 that's why I brought up this issue. However, the correct PHP version was in my Vagrant box and I was running a PHP command outside the box which is not the correct version. All good!

**Comment by Ocramius** [comment]
@yellowmamba alright :+1:
