### ISSUE TITLE
Must be an instance of ProxyManager\void, none returned

### ISSUE THREAD

**Issue by Tomsgu** [Ocramius/ProxyManager#362]
Hi,

I am getting a strange error here. I use symfony3 and everytime I make a change in my source code, I get this error:
`FatalThrowableError in Configuration.php line 124:
Type error: Return value of ProxyManager\Configuration::setGeneratorStrategy() must be an instance of ProxyManager\void, none returned`

But when I run symfony's clear cache command only with warmup it fixes the issue. But it should be run on each change.

Is it somehow related to this library? Or do you know where can be a problem? 

I am using:
ocramius/proxy-manager: 2.1.0 
php: 7.1.0

**Comment by Ocramius** [comment]
@Tomsgu you are running the code against PHP 7.0, not 7.1. Be aware that PHP-CLI and the PHP CGI/web SAPIs are different.

**Comment by Tomsgu** [comment]
Oh my goodness. So stupid. Thanks for the answer.
