### ISSUE TITLE
[Enhancement] Compatible signature for suffixInterceptor and prefixInterceptor

### ISSUE THREAD

**Issue by temple** [Ocramius/ProxyManager#372]
In my case, I'm in the need of implement a common invocation gateway for _suffix_ and _prefix_ _Interceptors_.

This is what I call an `InvokableAccessInterceptor`.

This interface provides a single "gateway" function what can be passed as _methodPrefixInterceptor_ and also a _methodSuffixInterceptor_.

But it faces a little problematic.
As [officially documented here](https://ocramius.github.io/ProxyManager/docs/access-interceptor-value-holder.html#implementing-pre--and-post--access-interceptors), _prefixInterceptor_ and _suffixInterceptor_ _Closures_ differ in param number and param order, even having a common part (first 4 arguments).

It forces me to define the _interceptorCommonGateway_ function as:

```php
function interceptorCommonGateway($proxy, $instance, $method, $params, & $prefix_returnEarly__or__suffix_returnValue = null, & $suffix_returnEarly = null)
```

This is a bit nasty, because it would be easier having a compatible signature for both interceptors signatures, what could be something like this:

```php
$prefixInterceptor = function($proxy, $instance, $method, $params, & $returnEarly);
$suffixInterceptor = function($proxy, $instance, $method, $params, & $returnEarly, $returnValue);
```

This common signature would let implementing _interceptorCommonGateway_  the following way
```php

interface InterceptorGateway
{
    /**
     * Does nothing more than determine the $isPrefixInterception argument value, and call actualInterception
     */
    function interceptorCommonGateway($proxy, $instance, $method, $params, & $returnEarly, $returnValue = null);

    function actualInterception($proxy, $instance, $method, $params, & $returnEarly, $isPrefixInterception = true,  $returnValue = null);
}
```

**Comment by Ocramius** [comment]
@temple I don't see a value in a single interface for this, since the behavior is explicitly different. Having a wrapper that creates interceptors for you, honoring whether they are prefix- or suffix- ones, would probably be better.

Also, default parameter values are to be avoided as a "hack" to compatibilize APIs, as they hide the differences in subtle details.

**Comment by temple** [comment]
I think I don't understand what you mean when you say
> Also, default parameter values are to be avoided as a "hack" to compatibilize APIs, as they hide the differences in subtle details.

Mission of the CommonGateway is just containing a dynamic call to prefixesInterceptions and suffixesInterceptions.

It lets the user define a reusable _Gateway_ Trait in [self-declared inteceptor invokable classes](https://github.com/Ocramius/ProxyManager/issues/370).

**Comment by Ocramius** [comment]
@temple you made the API have `$isPrefixInterception = true,  $returnValue = null` at the end of the signature: this means that this is not just 2 APIs in one, but 4 possible permutations. You also coded an "is-a" definition in the parameter.

As I already mentioned in #370, we will likely have interfaces for each of these closures, with the removal of `callable` support overall. A `PrefixInterceptor` and a `SuffixInterceptor`, having different semantics, parameters and behavior, will get two different interfaces. If you want to glue together pre- and post- steps, you will just need to implement both interfaces in your codebase.

**Comment by temple** [comment]
Ok, this is clear now for me.

Thank you for your patience

**Comment by Ocramius** [comment]
@temple :+1: 

Feel free to poke me if you want to start any work on this on your end - I have no time until Q3 2017, but then I should be able to start integrating this tool into Doctrine ORM, which also means time to fix the rough edges.

**Comment by temple** [comment]
Would be a honour, maybe you don't know, but I consider you a guru, since apigility sf2 integration

**Comment by Ocramius** [comment]
@temple I'm just an annoying internet person :-)

Feel free to poke me if you have questions and you want to give it a shot.

**Comment by temple** [comment]
I've a little cuestion about PHP 7.1, but where is the right place to ask you?

**Comment by Ocramius** [comment]
@temple on hangouts, via mail, on twitter, on irc.freenode.net (#doctrine, #roave, #zftalk), on [gitter](https://gitter.im/Ocramius/ProxyManager)
