### ISSUE TITLE
[Feature] [LazyLoadingValueHolderGenerator] Evaluate code directly that only accesses scope local variables

### ISSUE THREAD

**Issue by lstrojny** [Ocramius/ProxyManager#377]
Assume code like this:
```
class Foo {
    public function isSomething($obj): bool
    {
         return $obj instanceof Something;
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function isActive(): bool
    {
        return $this->returnsFalse();
    }

    private function returnsFalse(): bool
    {
        return false;
    }
}
```

It would be neat if we could avoid instantiating the proxy at all and simply evaluate the code locally.

@Ocramius  what do you think?

**Comment by Ocramius** [comment]
Not sure what you mean by "evaluate locally". You are probably looking for
ghost objects, which do what you want

**Comment by lstrojny** [comment]
@Ocramius I am referring to this as an optimization for code that doesn't depend on properties and non-local symbols (except on methods that have the same guarantees). I am thinking of e.g. Voters in Symfony.

This is the base class:

{code:php}
abstract class Voter implements VoterInterface
{
    public function vote(TokenInterface $token, $subject, array $attributes)
    {
        // abstain vote by default in case none of the attributes are supported
        $vote = self::ACCESS_ABSTAIN;

        foreach ($attributes as $attribute) {
            if (!$this->supports($attribute, $subject)) {
                continue;
            }

            // as soon as at least one attribute is supported, default is to deny access
            $vote = self::ACCESS_DENIED;

            if ($this->voteOnAttribute($attribute, $subject, $token)) {
                // grant access as soon as at least one attribute returns a positive response
                return self::ACCESS_GRANTED;
            }
        }

        return $vote;
    }

    abstract protected function supports($attribute, $subject);

    abstract protected function voteOnAttribute($attribute, $subject, TokenInterface $token);
{code}

Let’s assume an implementation like this:

{code:php}
class MyVoter extends Voter
{
    public function __construct(Dependency $dep)
    {
        $this->dep = $dep;
    }

    protected function supports($attribute, $subject)
    {
           return $attribute === self::LOCAL_SOMETHING;
    }

    protected function voteOnAttribute($attribute, $subject, TokenInterface $token)
    {
        return $this->dep->something();
    }
}
{code}

So a clever proxy could look like this:

{code}
class MyProxy extends MyVoter
{
    protected function voteOnAttribute($attribute, $subject, TokenInterface $token)
    {
           $this->doTheInitializationDance();
           return parent::voteOnAttribute($attribute, $subject, TokenInterface $token);
    }    
}
{code}

One would only fully initialize the proxied object once {{voteOnAttribute()}} is called. So we would not need to instantiate {{Dependency}} until {{voteOnAttribute()}} is invoked. The reason for that is: {{Voter::vote()}} does only access constant or local values (or calls another method) and {{Voter::supports()}} only accesses.

**Comment by Ocramius** [comment]
@lstrojny I already tried going down this way, but this requires method contents analysis that I cannot do without extremely complex AST traversal. Even the PHP engine doesn't do this sort of inspection.

There are scenarios where this can be applied:

 * pure methods (analyzing this is a mess)
 * methods that don't interact with properties in any way (also tricky, since property access in PHP doesn't happen only with the `->` operator)

I really wanted this too, but it is not feasible: a ghost object is a much better solution here.

**Comment by Ocramius** [comment]
Oh, and note that ghost objects do not add new stack frames at all, which means that they are even more efficient than what you are proposing. What would still be tricky is to capture constructor arguments, freeze them and then call the constructor when the proxy is first initialised (which isn't done in this library yet, but could be done)

**Comment by Ocramius** [comment]
Closing here: sticking to initial proposed solution

 >  a ghost object is a much better solution here.

A ghost object will only call its initializer if private state is accessed.

In fact, this is being discussed in 

 * https://github.com/symfony/symfony/issues/35345#issuecomment-576365888
 * https://github.com/symfony/symfony/issues/35345#issuecomment-576367311
 * https://github.com/symfony/symfony/issues/35345#issuecomment-748486601
