### ISSUE TITLE
Partly initialization

### ISSUE THREAD

**Issue by AndreRudolph** [Ocramius/ProxyManager#380]
Amazing and interesing project. I want to integrate your ProxyManager implementation into my project. However, I have a question about initialization of ValueHolderProxies. Is there any way to do a partly initialization depending on special use cases?

My use case:
I have a tree of objects. 

        <?php
        
        class Object {
            private $parent;
            private $childs;

            public function getParent() {
                return $this->parent;
            }

            public function getChilds() {
                return $this->childs;
            }
       }`

An object within the tree can be obtained by creating a virtual proxy. Each object has parent / child relationships to other objects and some other properties which should be initialized immediately. At the moment when an object will be obtained, a proxy for the object itself and proxies for the directly parent and child objects are created. So my question is: Is there any way to create these parent / child proxies if they are explicitly needed (e.g. if getParent is called) ?

Best regards

**Comment by Ocramius** [comment]
Partial loading is only possible with a [ghost object](https://github.com/Ocramius/ProxyManager/blob/5c8c273a171c58a432d990394f183d77685adb0b/docs/lazy-loading-ghost-object.md), although I didn't implement it fully yet, and I'm unsure about the proper interface for now.

You probably want exactly what @lstrojny wants in https://github.com/Ocramius/ProxyManager/issues/377

There is one way to achieve that, although it is very hacky and not formalised. As you can see in the [initializer signature](https://github.com/Ocramius/ProxyManager/blob/5c8c273a171c58a432d990394f183d77685adb0b/docs/lazy-loading-ghost-object.md#lazy-initialization), a method and a parameter list is available. If you check for usages of `__get`, `__set` or `__isset` and only load the properties you want, then unset the properties that shouldn't have been initialized, that *could* work, although I didn't try it myself.

I will at some point have to implement partial loading, as I really want the feature for Doctrine ORM too.

**Comment by AndreRudolph** [comment]
Thank you for your fast reply. Apparently you have planned to implement partial loading in future, so I can wait with this performance issue because it has not a high priority. The important thing is that it works and it works like a charm. 

Maybe it will reduces complexity in future if you could provide a way to use objects as initializer instead of closures. Closures for less complex and classes for more complex initialization logic.

Thank you very much.

**Comment by Ocramius** [comment]
> classes for more complex initialization logic.

That's the plan for a later version: since PHP anonymous classes are now available, I want to interface the initializer.

**Comment by AndreRudolph** [comment]
That's a good idea. Then I will use your library without worries. 👍

**Comment by Ocramius** [comment]
Note: the initializers are now interfaced correctly, although through psalm annotations.

https://github.com/Ocramius/ProxyManager/blob/f65ae0f9dcbdd9d6ad3abb721a9e09c3d7d868a4/src/ProxyManager/Factory/LazyLoadingGhostFactory.php#L78-L84
