### ISSUE TITLE
File name too long

### ISSUE THREAD

**Issue by gotu** [Ocramius/ProxyManager#388]
Getting this error with ocramius/proxy-manager 2.0.4 (on sulu/sulu 1.6.3) using ubuntu 16.04, php7.0:

`Could not write to path "/application/var/cache/admin/dev/sulu/proxies/ProxyManagerGeneratedProxy__PM__SuluComponentDocumentManagerDocumentUnknownDocumentGenerated6ba9e6da88c639a61276f3813626e37b.php.59b246012d98d0.05171805": path does not exist
`

File name is too long:
```
touch ProxyManagerGeneratedProxy__PM__SuluComponentDocumentManagerDocumentUnknownDocumentGenerated6ba9e6da88c639a61276f3813626e37b.php.59b246012d98d0.05171805
touch: cannot touch 'ProxyManagerGeneratedProxy__PM__SuluComponentDocumentManagerDocumentUnknownDocumentGenerated6ba9e6da88c639a61276f3813626e37b.php.59b246012d98d0.05171805': File name too long
```

**Comment by gotu** [comment]
so apparently the issue is that the filenames are too long for an encrypted drive

**Comment by Ocramius** [comment]
@gotu I think one fix could be to use `temnam()` and a random location instead of that final `.59b246012d98d0.05171805`.

A stack trace would be better though.

**Comment by Pittiplatsch** [comment]
Actually, I encountered the very same problem, but with Windows paths which are still limited to some 255 chars IIRC.
My workaround back then was to store the project very near to file system root, i.e. sth. like C:\project.

**Comment by Ocramius** [comment]
Another solution is to replace the naming strategy of ProxyManager, which
is configurable.
