### ISSUE TITLE
[Question] Is it possible to replace the $wrappedObject?

### ISSUE THREAD

**Issue by jon-frankel** [Ocramius/ProxyManager#397]
I have a use case where I need a proxy for the Doctrine2 entity manager. The problem I'm trying to solve is that when the entity manager closes, and is reopened, it does not use the original instance — it creates a new instance of the manager with a new connection. In that case, I would need to have $wrappedObject reference that new instance.

How would I accommodate that? Would it be possible to do something like `$proxy->setWrapped($newEM)`?

**Comment by Ocramius** [comment]
This can be dealt with in an access interceptor proxy, not in a lazy loading one.

**Comment by Ocramius** [comment]
Closing here: answered a long time ago.
