### ISSUE TITLE
Proxy method arg default value

### ISSUE THREAD

**Issue by StevioStudio** [Ocramius/ProxyManager#402]
I have a service with this method:
`public function getFacebookAuth(\AppBundle\Entity\User &$user = NULL, GraphUser $facebookUser)`
Proxy is generated like this:
`public function getFacebookAuth(\AppBundle\Entity\User &$user, \Facebook\GraphNodes\GraphUser $facebookUser)`

Is this a bug? 'Cause I need the first arg to be NULL sometimes and using proxy is breaking my app.

**Comment by Ocramius** [comment]
The signature above is not valid, because the first `= null` is succeeded by a non-optional parameter. This is fixed in PHP 7.1 and in release `2.1.0` by using a nullable type hint.

**Comment by StevioStudio** [comment]
You're right. My bad. I switched args order and it's working correctly.
