### ISSUE TITLE
Could not retrieve default argument from builtin methods/functions

### ISSUE THREAD

**Issue by Netmosfera** [Ocramius/ProxyManager#406]
PHP's reflection doesn't allow to retrieve the default argument from internal parameters.
ParameterGenerator::fromReflection just sets them to null if that's the case https://github.com/zendframework/zend-code/blob/6b1059db5b368db769e4392c6cb6cc139e56640d/src/Generator/ParameterGenerator.php#L81

In other words if the method signature is:
```
public function xxx(array $foo = []);
```
and the default argument for $foo can't be retrieved, the generated signature will be
```
public function xxx(array $foo = null)
```
if the arg is omitted at call time, when the proxy xxx delegates to the original xxx, it will do it like so
```
$original->xxx(null);
```
which causes an error in php (e.g. PDO::prepare() expects parameter 2 to be array, null given)
There is no clean solution for this, afaik.

A trick ProxyManager could use is silencing the LSP warnings when the proxy class is generated, like so:
https://3v4l.org/S82aR

Hope this helps.

**Comment by Ocramius** [comment]
Silencing is absolutely not an option. The correct solution would be to swap out the internal reflection with `BetterReflection`, which provides proper polyfilling where the reflection API fails on core functions/methods.

See also https://github.com/Ocramius/ProxyManager/issues/369
See also https://github.com/Ocramius/ProxyManager/issues/162

**Comment by Ocramius** [comment]
Closing as `duplicate` for now. #162 is the correct thread for this.

Work around swapping the reflection component is still in the works (https://github.com/Ocramius/ProxyManager/pull/243), but will likely be shipped in a new major version due to required configuration changes (it is too slow for most basic use-case scenarios).
