### ISSUE TITLE
PHP version constraints and semver

### ISSUE THREAD

**Issue by nesl247** [Ocramius/ProxyManager#407]
Is there any reason that PHP 7.1 support was dropped? It seems highly unusual and I would imagine it goes against semver to drop support for PHP 7.1 in a minor update (2.2.0).

**Comment by Ocramius** [comment]
See http://doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html

Bumping dependency versions is not a BC break (more in that page).

**Comment by xurshid29** [comment]
Ok, we understand that "Bumping dependency versions is not a BC break", but, anyway, what was the reason? Why can't you leave php7.1 version support? Sometimes it can be hard to manage the version of PHP on servers.

**Comment by Ocramius** [comment]
> Why can't you leave php7.1 version support?

Few reasons among the many:

 1. it's my weekend
 2. nobody is paying me to support an older version
 3. the reflection API changed, and I'm not supporting two different API systems
 4. the test suite would require multiple switches just to enable/disable testing of `object` hints

**Comment by xurshid29** [comment]
@Ocramius Ok, thanks for the answer
