### ISSUE TITLE
Update ocramius/package-versions

### ISSUE THREAD

**Issue by alanpoulain** [Ocramius/ProxyManager#410]
Could you please update (^1.1.3) your PackageVersions in the composer file?
It's a dependency (^1.2.0) of https://github.com/Jean85/pretty-package-versions used by phpstan.
And I need ProxyManager because of https://github.com/doctrine/migrations.
Thanks a lot!

**Comment by Ocramius** [comment]
`^1.1.3` includes `1.2.0`
