### ISSUE TITLE
Return value ?object of getWrappedValueHolderValue

### ISSUE THREAD

**Issue by twmobius** [Ocramius/ProxyManager#415]
On commit https://github.com/Ocramius/ProxyManager/commit/2c712a78278385c79f1959eed74ac81282b64318 return type `?object` has been added on the `getWrappedValueHolderValue()`.

On php 7.1 this commit causes my code to fail with error:

```
Return value of ProxyManagerGeneratedProxy\__PM__\App\Entity\Person\Generated44f659181cff78b41f2d2d744f492cfc::getWrappedValueHolderValue() must be an instance of ProxyManagerGeneratedProxy\__PM__\App\Entity\Person\object or null, instance of App\Entity\Person returned
```

There is something wrong with the namespaces here

**Comment by Ocramius** [comment]
If you check `composer.json`, the latest release of ProxyManager only supports PHP 7.2. you probably want to work on `2.1.*`
