### ISSUE TITLE
Have a "strict" mode where magic getters/setters are dumped as throwing methods

### ISSUE THREAD

**Issue by nicolas-grekas** [Ocramius/ProxyManager#418]
Could be especially useful when proxying base on an interface, to forbid using dynamic properties.
In this mode, using dynamic properties would throw an exception (unless __get/etc. are found in the proxied class/interface of course.)
Does this make sense?

**Comment by Ocramius** [comment]
Ghe current logic mimicks PHP's behaviour: I really wouldn't want to invent my own semantics, as the library should be transparency.

**Comment by Ocramius** [comment]
Also, I think this is already possible with an access interceptor with an interceptor on `__get`

**Comment by nicolas-grekas** [comment]
> Also, I think this is already possible with an access interceptor with an interceptor on __get

Great, then no need to keep this open, thanks.

**Comment by Ocramius** [comment]
@nicolas-grekas have you already seen https://github.com/InterNations/type-jail ?

**Comment by nicolas-grekas** [comment]
Nope, didn't know, now checking, thanks for the link.

**Comment by Ocramius** [comment]
@nicolas-grekas as far as I know, @lstrojny uses it to enforce getter-only-access in twig views
