### ISSUE TITLE
[2.1.x] FileWriterGeneratorStrategy:  File permission - compatibility problem when upgrading from 2.0.4 to 2.1+

### ISSUE THREAD

**Issue by danieltoader** [Ocramius/ProxyManager#432]
When updating from 2.0.4 to 2.1.* + the file permission for proxy generated files is forced to 0600 by the function _tempnam_ ( http://php.net/manual/ro/function.tempnam.php ).
> Creates a file with a unique filename, with access permission set to 0600, in the specified directory. If the directory does not exist or is not writable, tempnam() may generate a file in the system's temporary directory, and return the full path to that file, including its name.  

Prior to 2.1 the temporary file name was generated using :
`$tmpFileName   = $location . '.' . uniqid('', true);`
Starging with 2.1 it changed to :
`$tmpFileName = tempnam($location, 'temporaryProxyManagerFile');`

This breaks compatibility with previous versions. The fix should consist in either setting the correct permissions after using file_put_contents or revert back to the old file name generator for the 2.* version.

This pull request should fix the problem: https://github.com/Ocramius/ProxyManager/pull/421/commits even though i saw that it was argued that the pull request would actually break compatibility with previous versions.

Thanks,
Dan

**Comment by Ocramius** [comment]
That patch will indeed only land in 3.x

**Comment by Ocramius** [comment]
Note that I won't revert the change from `2.0` to `2.1`: yes, it may have been a BC break, but changing it again is another breaking mistake then, hence the 3.x milestone
