### ISSUE TITLE
Tuning for production 

### ISSUE THREAD

**Issue by Orkin** [Ocramius/ProxyManager#437]
Hello @Ocramius,

I would like to tune the proxy manager for production. I already wrote a command to generate my proxies to prevent write/read permissions problem on docker container.
I used Zend Expressive and the Zend Service Manager. Maybe I have missed something but by looking the code of the Service Manager all is already include between thoses both component. And for now I have write problem to the directory where are my proxies. But I don't understand why I have this case because my proxies are already generated and exists, the Zend Service Manager already register the autoload for proxies classes and in my config I have enabled the write of proxies class.

I have tried to disable the write proxies options to fix the problem but now proxies are generate on the fly and proxies files classes are not used.

Have you some advice to fix that ? Once again, I think I have missed something but I can't find it !

Thanks

**Comment by Ocramius** [comment]
I am not up to date on the `zend-servicemanager` integration. If it is already tuned, then you don't need to do anything there.

Is the issue that proxies are being written to disk at each load? I didn't fully understand the question, in that case.

**Comment by Orkin** [comment]
Hey thanks for your fast reply !

Yes it's exactly that, on each request proxies are written on the disk event they already exists.

I tried too, to add the register the autoload on my `index.php` to be sure it's execute but I have the same problem

**Comment by Ocramius** [comment]
That most likely needs to be checked/tested directly within `zend-servicemanager` then. Can you open an issue there? We'd need to somehow test it first...

**Comment by Orkin** [comment]
Yes of course

**Comment by Ocramius** [comment]
Fixed in https://github.com/zendframework/zend-servicemanager/issues/274#issuecomment-444452528
