### ISSUE TITLE
synfony integration

### ISSUE THREAD

**Issue by soufianez75** [Ocramius/ProxyManager#451]
I have an issue with proxymanager since this week end

PHP Fatal error:  Declaration of Symfony\\Bridge\\ProxyManager\\LazyProxy\\PhpDumper\\LazyLoadingValueHolderGenerator::generate(ReflectionClass $originalClass, Zend\\Code\\Generator\\ClassGenerator $classGenerator) must be compatible with ProxyManager\\ProxyGenerator\\LazyLoadingValueHolderGenerator::generate(ReflectionClass $originalClass, Zend\\Code\\Generator\\ClassGenerator $classGenerator): void in /var/www/xxxxxxxxxx/release-1.4.2-20190319084524/vendor/symfony/symfony/src/Symfony/Bridge/ProxyManager/LazyProxy/PhpDumper/LazyLoadingValueHolderGenerator.php on line 20

can you please check this issue thanks

**Comment by Ocramius** [comment]
Damn, this is my mistake, and I even marked the commit as BC Break, sorry :-(

https://github.com/Ocramius/ProxyManager/commit/b6f50fcc8ad5cf9c48a4e335e2967a04b2a2fd80

**Comment by Ocramius** [comment]
@soufianez75 wait, are you running with PHP 7.4?

I'll revert the patch for `: void` specifically.

See https://wiki.php.net/rfc/allow-void-variance for what's going on.
Other parameter types won't be reverted, as per https://wiki.php.net/rfc/covariant-returns-and-contravariant-parameters (pending implementation)

**Comment by Ocramius** [comment]
@soufianez75 can you please try out #452 before I release this?

**Comment by JayPe69** [comment]
Hello,

I just updated : 

https://github.com/Ocramius/ProxyManager/issues/451

```
Package operations: 0 installs, 1 update, 0 removals
  - Updating ocramius/proxy-manager (2.2.2 => 2.3.1):  Checking out 3be07227a0
```

However in symfony project : 

`> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

Fatal error: Uncaught Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "hasType" of class "ReflectionProperty". in C:\wamp64\www\piko\vendor\ocramius\proxy-manager\src\ProxyManager\ProxyGenerator\Util\Properties.php:91
Stack trace:
#0 [internal function]: ProxyManager\ProxyGenerator\Util\Properties::ProxyManager\ProxyGenerator\Util\{closure}(Object(ReflectionProperty))
#1 C:\wamp64\www\piko\vendor\ocramius\proxy-manager\src\ProxyManager\ProxyGenerator\Util\Properties.php(100): array_filter(Array, Object(Closure))
#2 C:\wamp64\www\piko\vendor\ocramius\proxy-manager\src\ProxyManager\ProxyGenerator\Util\UnsetPropertiesGenerator.php(29): ProxyManager\ProxyGenerator\Util\Properties->onlyPropertiesThatCanBeUnset()
#3 C:\wamp64\www\piko\vendor\ocramius\proxy-manager\src\ProxyManager\ProxyGenerator\LazyLoading\MethodGenerator\StaticProxyConstructor.php(35): ProxyManager\ProxyGenerator\Util\UnsetPropertiesGenerator::generateSnippet(Object(ProxyManager\ProxyGenerator\Util\Prope in C:\wamp64\www\piko\vendor\ocramius\proxy-manager\src\ProxyManager\ProxyGenerator\Util\Properties.php on line 91
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception`

**Comment by Ocramius** [comment]
Well, for that to work you need PHP 7.4, as `composer.json` states

**Comment by gamusta** [comment]
**composer install** command fixed the problem for me
