### ISSUE TITLE
Fix version php 7.4

### ISSUE THREAD

**Issue by seftomsk** [Ocramius/ProxyManager#454]
When I want to install symfony/migrations I get ocramius/proxy-manager 2.3.1 requires php ^7.4.0 -> your PHP version (7.3.3) does not satisfy that requirement. But php 7.4 unavailable yet

**Comment by Ocramius** [comment]
That is correct: 2.3.0 requires PHP 7.4 (see release notes).

If you need earlier PHP versions supported (yes, including current stable ones), check the other 2.x releases.

**Comment by Shade634** [comment]
- ocramius/proxy-manager 2.7.1 requires php 7.4.0 -> your PHP version (7.4.2) does not satisfy that requirement.

**Comment by Ocramius** [comment]
That is correct: you need `ocramius/proxy-manager` `2.8.0`.

**Comment by dadrych** [comment]
I have the same problem - PHP 7.4.5
`Package ocramius/proxy-manager at version 2.8.0 has a PHP requirement incompatible with your PHP version (7.4)`

**Comment by andrew-demb** [comment]
@dadrych do you have configured config.platform.php in composer.json?

**Comment by dadrych** [comment]
@andrew-demb yes, config.platform.php: "7.4"

**Comment by andrew-demb** [comment]
@dadrych this is the reason. 2.8.0 require php 7.4.1.

**Comment by azarual** [comment]
Hi there every one any help please about this ? thank you in advance
- ocramius/proxy-manager 2.7.1 requires php 7.4.0 -> your PHP version (7.4.7-dev) does not satisfy that requirement.
- Installation request for ocramius/proxy-manager (locked at 2.7.1) -> satisfiable by ocramius/proxy-manager[2.7.1].

**Comment by Ocramius** [comment]
@azarual you need `ocramius/proxy-manager:^2.8.0`: please read the release notes.

Ref: https://github.com/Ocramius/ProxyManager/releases/tag/2.7.1
Ref: https://github.com/Ocramius/ProxyManager/releases/tag/2.8.0

**Comment by r-ant-2468** [comment]
Is there a reason why this package has to be restrictive to php point releases rather than just major/minor php versions?

**Comment by Ocramius** [comment]
Yes: I even had to restrict it to `^7.4.1` to fix some issues around typed property lazy loading (and a separate release for `7.4.0` only)

In general, if you rely on older PHP versions, you can use an older version of this package, but I expect you (package consumer) to do your own homework and upgrade to latest and greatest if you want to use the new shiny improvements on this end.
