### ISSUE TITLE
ReflectionProperty::hasType

### ISSUE THREAD

**Issue by gigafoxweb** [Ocramius/ProxyManager#456]
Attempted to call an undefined method named "hasType" of class "ReflectionProperty"

http://php.net/manual/en/class.reflectionproperty.php

https://github.com/Ocramius/ProxyManager/blob/2.3.1/src/ProxyManager/ProxyGenerator/Util/Properties.php

**Comment by Ocramius** [comment]
Please check your PHP version: 2.3.0 requires PHP 7.4.

Also check your composer installation process.

**Comment by msphn** [comment]
Yeah requiring PHP 7.4 in a minor. Great idea!

**Comment by Ocramius** [comment]
@msphn please read through

**Comment by xlttj** [comment]
Hmm, is PHP 7.4 already out and stable? Can't find it on https://www.php.net/ChangeLog-7.php

**Comment by Ocramius** [comment]
No, it is not yet released

**Comment by xlttj** [comment]
So, I don't get it… What's the point in bumping dependency to a non-released version? ProxyManager seems to be required by Pimcore, which is based on Symfony. I get this error:

```

Reading /app/vendor/composer/installed.json
Writing lock file
Generating optimized autoload files
Endroid Installer detected project type "all"
Reading ./composer.lock
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
> post-update-cmd: Pimcore\Composer::postUpdate
> post-update-cmd: @symfony-scripts
> symfony-scripts: Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

Fatal error: Uncaught Error: Call to undefined method ReflectionProperty::hasType() in /app/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/Util/Properties.php:91
```

**Comment by Ocramius** [comment]
> What's the point in bumping dependency to a non-released version? 

Mostly facilitating downstream work on PHP-7.4 specific components, such as in `doctrine/orm`.

> ProxyManager seems to be required by Pimcore

At which version?
You can just rely on the previous stable release: pimcore itself surely doesn't lock you onto bleeding edge.


> I get this error:

This version should never be reached if your environment isn't capable of running it (that is what the composer SAT processing does for you).

**Comment by Ocramius** [comment]
As mentioned above though, read through https://github.com/Ocramius/ProxyManager/issues/455
