### ISSUE TITLE
Release Minor Version of 2.2

### ISSUE THREAD

**Issue by natec8** [Ocramius/ProxyManager#458]
Would it be possible to get this commit (see below) merged in to v2.2.2 and then bump to v2.2.3? I want to upgrade to v2.3.1, but I am on php7.3 and will not upgrade to php7.4 until it's officially released. 

https://github.com/Ocramius/ProxyManager/commit/d20817ffb8712b02a8d710673c581df2c3e259a4

Or if possible it would be great to get a lot of the features/fixes that have been added to v2.3, that don't require php7.4, added to a minor release of v2.2, so that those of us not using php7.4 nightlies can still have the features/fixes added to the newer versions.

**Comment by Ocramius** [comment]
Seems feasible :+1:

**Comment by josefsabl** [comment]
Is this expected to be merged anytime soon? Thank you.

**Comment by Ocramius** [comment]
I didn't work on this project over the past few weeks.

**Comment by josefsabl** [comment]
I added this to my composer.json to test the pull request and will try to use it for a while to fix the problem and see how it works. It will take me some time to acknowledge the functionality as it requires some server configuration.

```
"repositories": [
    {
      "type": "git",
      "url": "https://github.com/rsahlstrom/ProxyManager.git"
    }
],
"require": {
  "ocramius/proxy-manager": "dev-addChmodToFileGeneratorOn222 as 2.2.2"
}
```

**Comment by Ocramius** [comment]
Closing here: happening now, hopefully
