### ISSUE TITLE
FileWriterGeneratorStrategy problem with persmissions

### ISSUE THREAD

**Issue by josefsabl** [Ocramius/ProxyManager#459]
Hello, I use Doctrine ODM which internally uses this library in its 2.0 version (As I understand it).

We encountered a problem where our proxies are not writeable by our CLI script when they are generated by Web.

I isolated the problem like this:

- tempnam is used to generate temporary file here: `\ProxyManager\GeneratorStrategy\FileWriterGeneratorStrategy::writeFile` and it works with location of the file (looks like it expects writeable directory)
- but proxy filename is passed here `\ProxyManager\GeneratorStrategy\FileWriterGeneratorStrategy::generate`, thus falling to system temp fallback.
- the problem is that the system temp obviously does not have read permission for group set and as the resulting file is expected to work with the app group (different users for CLI and Web), it breaks.

**Comment by Ocramius** [comment]
Check if this is related: https://github.com/Ocramius/ProxyManager/issues/458

**Comment by josefsabl** [comment]
Yes, it is related indeed as this chmod in the FileWriterGeneratorStrategy resolves the problem.

Well, to be precise, I am not sure what version do the Doctrine DOM guys use as their dependency. My version doesn't have the chmod at all (My version is 2.2.2, but it is installed indirectly as dependency of Doctrine ODM). The patch #458 is not actually too important, I patch-fixed the problem by manually adding chmod($tmpFileName, 0664); to FileWriterGeneratorStrategy.

But I still think that the location should be fixed to not get into this problem in the first place :-)

**Comment by alcaeus** [comment]
> Well, to be precise, I am not sure what version do the Doctrine DOM guys use as their dependency.

We require `^2.2` for ODM.

**Comment by Ocramius** [comment]
> the system temp obviously does not have read permission for group set

You can use a different file locator: https://github.com/Ocramius/ProxyManager/blob/ba2d3a0bfe72ada4ecae1e1d1167e4b90dd3639a/src/ProxyManager/GeneratorStrategy/FileWriterGeneratorStrategy.php#L51

**Comment by josefsabl** [comment]
> You can use a different file locator:

Thanks for the suggestions, maybe Doctrine guys will use this hack as they overload the default FileLocator already anyway.

But I still think it is a bug in writeFile method as it expects a file path but works with is as with directory path. And now I noticed the 2.3 has this fix already. So nothing to do here.

Thank you for your time.

**Comment by josefsabl** [comment]
One last point as simply adding the \dirname didn't fix the issue. tempnam documentation doesn't say anything permissions but some comments state that:

> The file created by tempnam() will have file permissions that reflect the current umask applied to the default

But this doesn't seem to actually to be the case. Although the location is now correct and temporary file is created in the application temp, it still has permissions as if permissions of system temp were applied.

Will update this when we confirm this.

**Comment by josefsabl** [comment]
Looking forward to having this in 2.2 :-)

**Comment by alcaeus** [comment]
> Thanks for the suggestions, maybe Doctrine guys will use this hack as they overload the default FileLocator already anyway.

That isn't possible. While we can change the file name in the file locator, the logic in the `FileWriterGeneratorStrategy` is always the same: write the file to a temp location, then move it to the actual filename returned from the file locator. This is done to ensure atomic writes in a concurrent environment, as `move` operations across the same partition are atomic in most file systems, while write operations often are not.
