### ISSUE TITLE
Clearer error messaging when composer.lock is not found

### ISSUE THREAD

**Issue by 9ae8sdf76** [Ocramius/ProxyManager#460]
In `PackageVersions::getComposerLockPath()` the code looks for `composer.lock` file in two locations: 

1. `__DIR__ . '/../../../../../composer.lock'` - the top-level project's root directory
1. `__DIR__ . '/../../composer.lock'` - the `package-versions` root directory inside of vendor

If neither directory has a composer.lock, then an exception is rightfully thrown. However, in `PackageVersions::getVersion()`, if the top-level project doesn't have a composer.lock file, then the error message could (and in my case does) end up throwing an exception stating `Required package "ocramius/proxy-manager" is not installed: cannot detect its version"`.

I accidentally stumbled across this error because I was deploying my code, sans the lock files, not knowing that the `package-versions` needs the lock file. To save some other developer the same troubles I've gone through, I'd like to request one of two possible solutions:

1. (Simple fix) Change the exception message in `PackageVersions::getVersion()` to suggest that the top-level composer.lock may be missing
2. (Possibly more complex?) Throw an exception from `PackageVersions::getComposerLockPath()` when the top-level composer.lock isn't found

I can appreciate that the latter may not be possible, and that I simply do not understand why it would fall back to using the `package-versions`' version of composer.lock.

Thank you. I will now "fix my shit" and deploy my lock files with my code. ;-)

**Comment by Ocramius** [comment]
Lock file is super important: make sure it is always shipped with your project, since a lot depends on it.

Meanwhile, closing here: this is solely a problem of `PackageVersions`. If you know how to improve resiliency there, please send a patch 👍

**Comment by 9ae8sdf76** [comment]
Shoot. I meant to open this in PackageVersions. My apologies. :)

**Comment by Ocramius** [comment]
Ah, another idea: consider looking under `vendor/composer/installed.json`

**Comment by kojidev** [comment]
@Ocramius can you please clarify what depends on `composer.lock` after `composer install`? It was working fine before now its throws this error

**Comment by Ocramius** [comment]
It uses the current version to hash part of the generated proxy class names: this ensures that upgrades in the library do lead to new proxies, and stale ones are ignored.

Besides that, please report any issues in the upstream library, if it is an actual bug.
