### ISSUE TITLE
Invalid Redis Proxy

### ISSUE THREAD

**Issue by puku** [Ocramius/ProxyManager#461]
I'm not sure if this issue should be fixed on the ProxyManager side, but maybe you have some nice ideas on how it can be fixed or some advice.

I'm using `PHP 5.6`, `Redis 4.3` and `Symfony 3.4`.

Everything is working fine without `ProxyManager`, but when I try to install `ProxyManager`(actually I need [doctrine/migrations](https://github.com/doctrine/migrations), which requires `ProxyManager`) I'm facing an issue.

`ProxyManager` creates a proxy class for the `\Redis` class of the [phpredis](https://github.com/phpredis/phpredis) extension. `\Redis` class contains method [`echo()`](https://github.com/phpredis/phpredis/blob/develop/php_redis.h#L36), which doesn't bring any problems by itself, but when a proxy object is created I'm getting the following error:

```
Parse Error: syntax error, unexpected 'echo' (T_ECHO), expecting identifier (T_STRING)  
```

The problem occurs, because keywords(such as `echo`) can not be used as names for `PHP` version less than `PHP 7`.

Here is an example of the generated proxy class:

```php
<?php

class Redis_ca5fc0f extends \Redis implements \ProxyManager\Proxy\VirtualProxyInterface
{

    ...

    /**
     * {@inheritDoc}
     */
    public function echo($msg)
    {
        $this->initializerca5fc0f && ($this->initializerca5fc0f->__invoke($valueHolderca5fc0f, $this, 'echo', array('msg' => $msg), $this->initializerca5fc0f) || 1) && $this->valueHolderca5fc0f = $valueHolderca5fc0f;

        return $this->valueHolderca5fc0f->echo($msg);
    }

    /**
     * {@inheritDoc}
     */
    public function eval($script, $args = null, $num_keys = null)
    {
        $this->initializerca5fc0f && ($this->initializerca5fc0f->__invoke($valueHolderca5fc0f, $this, 'eval', array('script' => $script, 'args' => $args, 'num_keys' => $num_keys), $this->initializerca5fc0f) || 1) && $this->valueHolderca5fc0f = $valueHolderca5fc0f;

        return $this->valueHolderca5fc0f->eval($script, $args, $num_keys);
    }

    ...

}
```

**Comment by Ocramius** [comment]
This is a problem of `Redis` itseld, usually solved by upgrading to a maintained PHP release.

Related: https://github.com/snc/SncRedisBundle/issues/442#issuecomment-446560529

See also https://3v4l.org/D2gl3

Your immediate resolution path is to get rid of PHP 5.6 as soon as possible, since it is EOL'd.
