### ISSUE TITLE
ocramius/package-versions 1.5.1 requires php ^7.3.0 -> your PHP version (7.2.16) does not satisfy that requirement.

### ISSUE THREAD

**Issue by aligurbuz** [Ocramius/ProxyManager#474]
**I am constantly having this problem. So my 7.1 and 7.2 tests fail. What is the solution?**

Problem 1
    - Installation request for ocramius/package-versions 1.5.1 -> satisfiable by ocramius/package-versions[1.5.1].
    - ocramius/package-versions 1.5.1 requires php ^7.3.0 -> your PHP version (7.2.16) does not satisfy that requirement.
  Problem 2
    - ocramius/package-versions 1.5.1 requires php ^7.3.0 -> your PHP version (7.2.16) does not satisfy that requirement.
    - ocramius/proxy-manager 2.2.2 requires ocramius/package-versions ^1.1.3 -> satisfiable by ocramius/package-versions[1.5.1].
    - Installation request for ocramius/proxy-manager 2.2.2 -> satisfiable by ocramius/proxy-manager[2.2.2].

**Comment by Ocramius** [comment]
What's your `composer.json`?

**Comment by aligurbuz** [comment]
sorry ocramius, recorded as ocramius / proxy manager in composer.json: 1.0 | 2.0.
ocramius / proxy-manager works when I remove the key.

**Comment by Ocramius** [comment]
Didn't understand that: whay was your `composer.json` like?

**Comment by aligurbuz** [comment]
"require": {
        "ocramius/proxy-manager": "1.0|2.0",
}

He was registered like that.
I think this package is loading other dependencies, so it has problems with me.
When I uninstall the package it started working without error.

**Comment by Ocramius** [comment]
If you ran `composer update` on a 7.3+ system, and then ran `composer install` on a `7.0+` system, then this is expected: your `composer.lock` is not compatible with your deployment environment.
