### ISSUE TITLE
Drop compiled documentation

### ISSUE THREAD

**Issue by Ocramius** [Ocramius/ProxyManager#488]
As discussed briefly with @malukenho, the compiled docs (in the `gh-pages` branch) can probably be dropped in favour of just letting folks browse the `.md` files (which render quite nicely).

Given the amount of added dependencies coming in through the build tools used for publishing these pages, I think @malukenho's suggestion is sound.

Having a webpage is quite redundant right now: maybe we can just set up a redirect on 404, pointing to the repository `docs/` dir?

**Comment by Ocramius** [comment]
@malukenho assigned to you just to have your opinion.

**Comment by malukenho** [comment]
I fully agree on that, I will pick this one up.

**Comment by Ocramius** [comment]
@malukenho no need for it: I just needed your opinion 👍

**Comment by Ocramius** [comment]
Handled in #490 and #491
