### ISSUE TITLE
Tag release to support PHP 7.4

### ISSUE THREAD

**Issue by ruudk** [Ocramius/ProxyManager#538]
First of all, thanks for this amazing package and your hard work on this. 

We're running PHP 7.4 in production and see this deprecation popping up:
```
PHP Deprecated:  Function ReflectionType::__toString() is deprecated in /var/www/app/vendor/ocramius/proxy-manager/src/ProxyManager/Generator/Util/ProxiedMethodReturnExpression
```

I know this has been fixed in master so this issue is to ask if there is an ETA on a new tagged release. I expect more people to encounter this issue on PHP 7.4.

For now I will ignore/filter this error message on my side.

**Comment by Ocramius** [comment]
Hmm, I thought I had already released this: what version are you on?

**Comment by ruudk** [comment]
I feel so stupid. I still had `config.platform.php = 7.3` in my `composer.json`. Therefore it didn't update from 2.2.3 to 2.5.0. Hope this helps somebody else in the future.

**Comment by gnutix** [comment]
I get this on `2.2.3` as I'm still running PHP 7.2. :(

**Comment by Ocramius** [comment]
`2.2.3` should be alright on `7.2`: are you 100% sure about all versions you deploy against? Otherwise, can you provide a reproducer/failing test on PHP 7.2?

**Comment by gnutix** [comment]
The deprecation happens when I run PhpStan through their https://hub.docker.com/r/phpstan/phpstan Docker image, which is on PHP 7.4 ! Any idea what I could do about it, except having my own Docker image for PhpStan based on PHP 7.2 ?
