### ISSUE TITLE
BC Break in 2.2.2? - Problem with get_func_args() and method with default parameters

### ISSUE THREAD

**Issue by pedro-stanaka** [Ocramius/ProxyManager#539]
Hi, thanks for the library in first place and for the work put on it.

I use this library at my company and during one upgrade from 2.2.1 to 2.2.2 I noticed that my tests started failing.

After some investigation I discovered that the problem was that in 2.2.2 it was introduced a change on `\ProxyManager\ProxyGenerator\RemoteObject\MethodGenerator\RemoteObjectMethod` to use `\func_get_args` instead getting each parameter and return one array of this.
I understand that the purpose was to support variadic parameters, but can the library maybe provide a way to still keep the default parameters?

Is there a better way to solve this? For now I had to drop my optional parameter and make it required.

**Comment by Ocramius** [comment]
Ouch: I'm indeed aware that there was a BC break because of that, but I did weigh it against the library being completely unusable with variadic arguments otherwise.

See https://github.com/Ocramius/ProxyManager/pull/434

If you have a scenario that no longer works, let's please look at it, and let's get it fixed, if possible.

Also note that `func_get_args()` is a quick & dirty solution: if more precise codegen can be used, we can probably go with that 👍

**Comment by Ocramius** [comment]
To be precise, I'd need a test case. Please look at https://github.com/Ocramius/ProxyManager/tree/master/tests/language-feature-scripts for examples

**Comment by pedro-stanaka** [comment]
Something like that would do the job (ran it locally): https://github.com/pedro-stanaka/ProxyManager/blob/bug-default-params-remote-object-method/tests/language-feature-scripts/remote-object-json-adapter-passes-default-parameters-correctly.phpt

Just as a context I am maintaining an internal fork of this library: https://github.com/cosminseceleanu/RestClientBundle and using the RemoteObjectFactory.
Specific class: https://github.com/cosminseceleanu/RestClientBundle/blob/master/Factory/RestProxyFactory.php

What I could come up with that could solve my problem (but looks dirty) is something like this: 
https://gist.github.com/d3fdd5ecebd396635ab23eebf22313e6

Thanks for your prompt reply!

**Comment by Ocramius** [comment]
If I understand it correctly, if `count(func_get_args()) < count(declared_args())` then we merge something?

**Comment by pedro-stanaka** [comment]
Yeah, exactly. If the number of declared parameters is greater than what we have on call, we merge default values in.

**Comment by pedro-stanaka** [comment]
If you give me some kind of input on what is the closest way to the library to solve the problem I am open to submit pull request. Or if I can configure the factory somehow to use another RemoteObjectMethod class implemented on my side, would work for me as well.

**Comment by Ocramius** [comment]
I think patching it here makes most sense: see https://github.com/Ocramius/ProxyManager/blob/2.5.1/src/ProxyManager/ProxyGenerator/RemoteObject/MethodGenerator/RemoteObjectMethod.php

What is needed is additional tests around methods with default values, methods with variadic arguments and methods called with a dynamic amount of arguments

**Comment by Ocramius** [comment]
Note: I don't think that other classes need adjustments: only the code generator and added tests

**Comment by Ocramius** [comment]
Handled in #540
