### ISSUE TITLE
What is a point for req php 7.4 ?

### ISSUE THREAD

**Issue by zorn-v** [Ocramius/ProxyManager#554]
For ALL versions that does not required it at all. Previously it was 7.3 for some new versions. In some projects I just set `composer config platform.php 7.2.5` coz old ubuntu etc. 7.3 currently on debian buster and ubuntu 19.20 - no problem. But 7.4 is bleeding edge now and I don't want to install it from 3dparty repos or compile it by hands or set `platform.php` on all my projects depends from this package (transitional, like doctrine migrations).

Marco, you are egoist )

**Comment by Ocramius** [comment]
7.4 is current stable, and implementing support for it was a lot of effort, requiring custom code to be introduced to support typed properties: that code should not be conditionally enabled nor conditionally tested.

Besides that, there are no excuses not to put your best efforts in keeping your software up to date.

**Comment by zorn-v** [comment]
Why before some versions require 7.3 and now no one ?

**Comment by Ocramius** [comment]
Previous releases did work with 7.3: the new code does not work on 7.3 or lower.

**Comment by zorn-v** [comment]
Sorry, I get. Your busines is to get "enterprise compatibility". Just change version number in your `package.json` and you get many new orders :smile:

**Comment by Ocramius** [comment]
My total gross revenue from OSS over the last decade has been ~2000€, so I'd say you should stop insinuating things and be thankful for the service being provided thus far, free of charge.
