### ISSUE TITLE
Package zendframework is abandoned, you should avoid using it. Use laminas

### ISSUE THREAD

**Issue by MaryanShvets** [Ocramius/ProxyManager#555]
Hi

Can't install using composer

According https://www.zend.com/blog/what-status-zend-framework-transition-laminas
Package zendframework is abandoned, you should avoid using it. Use laminas

Package zendframework/zend-eventmanager is abandoned, you should avoid using it. Use laminas/laminas-eventmanager instead.

Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.

**Comment by Ocramius** [comment]
`2.6.0` is already updated to use laminas.
