### ISSUE TITLE
`zend-code` and `zend-eventmanager` are abandoned packages: What to do?

### ISSUE THREAD

**Issue by Aerendir** [Ocramius/ProxyManager#556]
This issue is just to alert that the two packages are now abandoned ❤️

**Comment by andrew-demb** [comment]
`2.6.0` is already updated to use laminas.

Fixed in #546

**Comment by vkhramtsov** [comment]
It is possible to update requirements (replace zend with laminas) for old versions? Currently`symfony/proxy-manager-bridge` 4.4.2 (and 5.0.2) still require `ocramius/proxy-manager: ~2.1`  (in version 3.4 `ocramius/proxy-manager: ~0.4|~1.0|~2.0`).
I've created issue in symfony repository too https://github.com/symfony/symfony/issues/35300

**Comment by Ocramius** [comment]
No: changes in dependencies (any dependencies) in patch releases are not possible.

Besides, there is absolutely no problem in still using `zendframework/*` packages: they won't be un-published, and will stay as they are.

**Comment by vkhramtsov** [comment]
So new releases for old branches possible? Thank you for answer

**Comment by Ocramius** [comment]
New releases for old branches are possible, but **NOT** dependency changes. Patch updates must be possible for all consumers, and changing dependencies in a patch release denies that.

**Comment by vkhramtsov** [comment]
ok
