### ISSUE TITLE
Class 'Zend\Code\Generator\ClassGenerator' not found

### ISSUE THREAD

**Issue by BenMorel** [Ocramius/ProxyManager#559]
Version 2.2.3 of this package relies on `zendframework/zend-code`.
But `laminas/laminas-code` is wrongly [marked as replacing](https://github.com/laminas/laminas-code/blob/8499ce005b4c028af6c9e6145a27b6ea5d3c716b/composer.json#L67-L69) `zendframework/zend-code`.

And this is obviously wrong. Relying on ocramius/proxy-manager now throws:

> Class 'Zend\Code\Generator\ClassGenerator' not found

I just file a bug at https://github.com/laminas/laminas-code/issues/37.

Manually installing `laminas/laminas-zendframework-bridge` works.

Do you want to provide a quickfix by either requiring `laminas/laminas-zendframework-bridge` or restricting the `zendframework/zend-code` version to prevent laminas from being installed?

Or do you want to do nothing and just rely on laminas to fix their bug?

**Comment by Ocramius** [comment]
I'd say this is an upstream bug: in theory, laminas provides migration by rewriting references just in time, but anyway, the newer release should also replace zf and import laminas instead

**Comment by BenMorel** [comment]
Thank you. Actually, laminas did it right, and already requires the bridge.

I think this is actually an issue with composer:

https://github.com/laminas/laminas-code/issues/37#issuecomment-578321299

**Comment by mmoreram** [comment]
@Ocramius I think that the issue is still a thing in `php7.3`. Newer versions require `php7.4`

**Comment by Ocramius** [comment]
The laminas dependencies should work with 7.2+

**Comment by mmoreram** [comment]
I'm having some troubles with that, precisely, inside a php7.3 docker image. I check and I don't really have that code in my vendors.

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "ClassGenerator" from namespace "Zend\Code\Generator".
Did you forget a "use" statement for "Laminas\Code\Generator\ClassGenerator"? in /var/www/vendor/ocramius/proxy-manager/src/ProxyManager/Generator/ClassGenerator.php:15
Stack trace:
#0 /var/www/vendor/symfony/debug/DebugClassLoader.php(163): include()
#1 [internal function]: Symfony\Component\Debug\DebugClassLoader->loadClass('ProxyManager\\Ge...')
#2 /var/www/vendor/symfony/proxy-manager-bridge/LazyProxy/PhpDumper/ProxyDumper.php(122): spl_autoload_call('ProxyManager\\Ge...')
#3 /var/www/vendor/symfony/proxy-manager-bridge/LazyProxy/PhpDumper/ProxyDumper.php(83): Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\ProxyDumper->generateProxyClass(Object(Symfony\Component\DependencyInjection\Definition))
#4 /var/www/vendor/symfony/dependency-injection/Dumper/PhpDumper.php(512): Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\ProxyDumper->getProxyCode(Object(Symfony\Compo in /var/www/vendor/ocramius/proxy-manager/src/ProxyManager/Generator/ClassGenerator.php on line 15
```

**Comment by mmoreram** [comment]
Is OK.
I was having some problems related to composer under the image.
Sorry :/

**Comment by dkarlovi** [comment]
Getting this error when using via Symfony's ProxyBridge 4.4:

```
  Fatal error: Could not check compatibility between Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\LazyLoadingValueHolderGenerator::generate(ReflectionClass $originalClass, Zend\Code\Gen  
  erator\ClassGenerator $classGenerator): void and ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator::generate(ReflectionClass $originalClass, Laminas\Code\Generator\ClassGenerat  
  or $classGenerator), because class Zend\Code\Generator\ClassGenerator is not available in /var/www/html/vendor/symfony/symfony/src/Symfony/Bridge/ProxyManager/LazyProxy/PhpDumper/LazyLoa  
  dingValueHolderGenerator.php on line 33
  ```

Seems they should either conflict with the newer versions of ProxyManager, fix the signature (it's in an `@internal` class) or require the ZF / Laminas bridge?

**Comment by Ocramius** [comment]
Hey @dkarlovi - Symfony core has marked my comment as "disruptive", because frankly any cooperation has completely failed there, but this problem is known and discussed at https://github.com/symfony/symfony/issues/41742#issuecomment-863896509

Ref: https://github.com/laminas/laminas-code/issues/89#issuecomment-864161193
Ref: https://github.com/symfony/symfony/issues/41742#issuecomment-863896509

**Comment by dkarlovi** [comment]
Alright, will read through those, requiring `laminas/laminas-zendframework-bridge` yourself seems to fix the issue for any Google passers by in the meantime.
