### ISSUE TITLE
Is it possible to get a 2.2.x release with Laminas packages?

### ISSUE THREAD

**Issue by k00ni** [Ocramius/ProxyManager#560]
Unfortunately, there is no ProxyManager release, which only requires PHP 7.3.x and uses Laminas packages to replace the Zend ones. You directly jumped to ProxyManager 2.5.0 and require PHP 7.4 (previously 7.2). I can't upgrade to 2.5 yet, because PHP 7.3.x runs on my machine, but i would like to get rid of these abandoned infos.

Is it possible to get a 2.x release, which uses Laminas packages, but only require PHP 7.2 or 7.3?

**Comment by Ocramius** [comment]
Dependency changes in patch releases are out of question, sorry. Nothing wrong with relying on `zendframework/` packages, as they are stable and will not be removed anyway.

**Comment by Ocramius** [comment]
BTW, I removed all branches before `2.6.x`: those are unmaintained, unless a security issue pops up.

Upgrading to 7.4 is now generally viable.

**Comment by k00ni** [comment]
Ok, thank you for the clarification.
