### ISSUE TITLE
Possibility to use laminas with php 7.3.*

### ISSUE THREAD

**Issue by parktrip** [Ocramius/ProxyManager#561]
Dear @Ocramius, 
at the moment it is not possible to use this package with laminas and php 7.3. Migration to Laminas was made on a version that only supports 7.4.
Will you accept a PR that gives this possibility ? I think 2.2 branch should be used in this case.

regards,

**Comment by Ocramius** [comment]
Hey @parktrip, this is a duplicate of #560.

**Comment by parktrip** [comment]
my bad, the worstis that I have read yesterday #560 and didn't understand it was also solving my issue. sorry again. have a nice day

**Comment by Ocramius** [comment]
No worries, thanks for your understanding :+1:
