### ISSUE TITLE
  PHP Fatal error:  Uncaught Error: Class 'Zend\Code\Generator\ClassGenerator' not found in /tmp/build_60c2c0696c901bed5e0db479a4213abe/vendor/ocramius/proxy-manager/src/ProxyManager/Generator/ClassGenerator.php:15

### ISSUE THREAD

**Issue by pesseyjulien** [Ocramius/ProxyManager#569]
Hi,

I have this error on prod with php7.4 but no error on local with php7.2

Any idea why ?

**Comment by Ocramius** [comment]
Got a full trace?

**Comment by pesseyjulien** [comment]
Executing script php bin/console cache:clear [KO]
        [KO]
       Script php bin/console cache:clear returned with error code 255
       !!  PHP Fatal error:  Uncaught Error: Class 'Zend\Code\Generator\ClassGenerator' not found in /tmp/build_60c2c0696c901bed5e0db479a4213abe/vendor/ocramius/proxy-manager/src/ProxyManager/Generator/ClassGenerator.php:15
       !!  Stack trace:
       !!  #0 /tmp/build_60c2c0696c901bed5e0db479a4213abe/vendor/composer/ClassLoader.php(444): include()
       !!  #1 /tmp/build_60c2c0696c901bed5e0db479a4213abe/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
       !!  #2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
       !!  #3 /tmp/build_60c2c0696c901bed5e0db479a4213abe/vendor/symfony/symfony/src/Symfony/Bridge/ProxyManager/LazyProxy/PhpDumper/ProxyDumper.php(126): spl_autoload_call()
       !!  #4 /tmp/build_60c2c0696c901bed5e0db479a4213abe/vendor/symfony/symfony/src/Symfony/Bridge/ProxyManager/LazyProxy/PhpDumper/ProxyDumper.php(87): Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\ProxyDumper->generateProxyClass()
       !!  #5 /tmp/build_60c2c0696c901bed5e0db479a4213abe/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php(508): Symfony\B in /tmp/build_60c2c0696c901bed5e0db479a4213abe/vendor/ocramius/proxy-manager/src/ProxyManager/Generator/ClassGenerator.php on line 15
       !!  
       Script @auto-scripts was called via post-install-cmd
 !     WARNING: There was a class not found error in your code
 !     ERROR: Dependency installation failed!

**Comment by pesseyjulien** [comment]
- Installing ocramius/proxy-manager (2.2.3): Loading from cache

**Comment by pesseyjulien** [comment]
I had to add "laminas/laminas-zendframework-bridge" : "@stable" in my composer.json, now it works..

**Comment by Ocramius** [comment]
If reproducible, I would suggest reporting an issue in `laminas/laminas-zendframework-bridge`

**Comment by pesseyjulien** [comment]
yes, thanks !
