### ISSUE TITLE
Setting public property has no effect

### ISSUE THREAD

**Issue by sakarikl** [Ocramius/ProxyManager#575]
Example code:

```php

<?php
declare(strict_types=1);
namespace TEST_PHP;

require_once __DIR__ . '/vendor/autoload.php';
ini_set('date.timezeone', 'Europe/Helsinki');

class PublicPropertyTest
{
    /**
     * @var string
     */
    public $variable;

    public function test()
    {
        echo PHP_EOL . 'in test function';
    }
}

$proxyFactory = new \ProxyManager\Factory\LazyLoadingValueHolderFactory();

/** @var PublicPropertyTest $test */
$test = $proxyFactory->createProxy(
    '\TEST_PHP\PublicPropertyTest',
    function (&$service, $proxy, $method, $parameters, &$initializer) {
        $service = new \TEST_PHP\PublicPropertyTest();
        $service->variable = 'set while initialized';

        return true;
    }
);
echo PHP_EOL . $test->variable;
$test->variable = 'changed 1';
echo PHP_EOL . $test->variable;
$test->test();
echo PHP_EOL . $test->variable;
$test->variable = 'changed 2';
echo PHP_EOL . $test->variable;

echo PHP_EOL;
```

output:

```
set while initialized
set while initialized
in test function
set while initialized
set while initialized

 ```

Expected output:

```
set while initialized
changed 1
in test function
changed 1
changed 2
```

**Comment by sakarikl** [comment]
With 2.7.0 and php 7.4.3

php -v
PHP 7.4.3 (cli) (built: Feb 18 2020 11:53:05) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
with Xdebug v2.9.3, Copyright (c) 2002-2020, by Derick Rethans

**Comment by Ocramius** [comment]
The `&$initializer` must be set to null:

```php
$test = $proxyFactory->createProxy(
    '\TEST_PHP\PublicPropertyTest',
    function (&$service, $proxy, $method, $parameters, &$initializer) {
        $initializer = null;
        $service = new \TEST_PHP\PublicPropertyTest();
        $service->variable = 'set while initialized';

        return true;
    }
);
```

Also, in theory you shouldn't need the `/** @var */` annotations: both IDE and psalm should be able to infer correct types

**Comment by sakarikl** [comment]
Same results with setting $initializer to null 

PHPStorm doesn't understand correct types without @var tags

**Comment by Ocramius** [comment]
> Same results with setting $initializer to null

Can you check if the given class name affects this? I see that the string you are providing to the factory has an excessive `"\"` in front of it.

Also: run psalm on your snippet to see if any type issues arise.

> PHPStorm doesn't understand correct types without @var tags

Check if https://github.com/Ocramius/ProxyManager/blob/master/.phpstorm.meta.php exists in your `vendor/`

**Comment by sakarikl** [comment]
Same results still after fixing that.

I have that .phpstorm.meta.php

**Comment by Ocramius** [comment]
See #576: I can't reproduce your issue there, but please adapt the tests if you see something mismatching.

**Comment by sakarikl** [comment]
Ok this was my bad. Didn't set initializer properly to null...

**Comment by Ocramius** [comment]
Yeh, that was mentioned in https://github.com/Ocramius/ProxyManager/issues/575#issuecomment-600500495 :) 

Glad it's solved!
