### ISSUE TITLE
Autoload imported annotations classes in proxy when using EvaluatingGeneratorStrategy

### ISSUE THREAD

**Issue by sidux** [Ocramius/ProxyManager#584]
Hi, 

Im facing an issue where an annotation in my original class fail to autoload, when using `EvaluatingGeneratorStrategy` i also noticed that all other imports got replaced by FQCN except for the annotation.

Any ideas ?

Thanks

**Comment by Ocramius** [comment]
> i also noticed that all other imports got replaced by FQCN except for the annotation.

Could you clarify? Proxy classes are not supposed to be scanned for annotations, and in fact should have `{@inheritDoc}` on most of their declared API.

**Comment by sidux** [comment]
i see thank you, actually it was a custom implementation of `ProxyGeneratorInterface` from an other library that i was dealing with.
