### ISSUE TITLE
Replace current test suite with github actions

### ISSUE THREAD

**Issue by Ocramius** [Ocramius/ProxyManager#588]
The current build status is in a sod state:

 * external tools all have their own versioning scheme
 * very slow builds
 * hooks fire sometimes, other times need to look up build statuses manually

I guess it's really time to move to github actions...

**Comment by stof** [comment]
@Ocramius I guess the title of this issue is wrong (gitlab vs github)
And this should be considered fixed by #601

**Comment by malukenho** [comment]
Thank you for noticing!
