### ISSUE TITLE
getWrappedValueHolderValue function problem

### ISSUE THREAD

**Issue by niksa88** [Ocramius/ProxyManager#598]
Hi,

I need some help/explation how getWrappedValueHolderValue function work.
I have some weird situation where getWrappedValueHolderValue return NULL instead object.

First example when NULL is returned but after the object function is called and it return object ID

    if ($value instanceof ValueHolderInterface) {
        var_dump($value->getWrappedValueHolderValue()); // return NULL
        var_dump($value->getId()) // return object ID
    }

Second example where after calling function on object the valid object is returned for wrapped value.

    if ($value instanceof ValueHolderInterface) {
        var_dump($value->getId()) // return object ID
        var_dump($value->getWrappedValueHolderValue()); // return object
    }

I don't have this situation every time when getWrappedValueHolderValue is called but I don't know how to figure why function does not return object.

If somebody have some advice I would be grateful.

Thanks

**Comment by Ocramius** [comment]
That would depend on how your initializer closure is written.

In any case, accessing the wrapped value should not be needed, and could be avoided.

**Comment by niksa88** [comment]
> That would depend on how your initializer closure is written.
> 
> In any case, accessing the wrapped value should not be needed, and could be avoided.

Thanks for the help, it was my mistake. The proxy was not initialized.
