### ISSUE TITLE
Run CI under php nightly version?

### ISSUE THREAD

**Issue by malukenho** [Ocramius/ProxyManager#605]
I couldn't make a way to "allow failure" under a PHP `8.0` — as they call the nightly version.

If one of the matrix cases fails, it halts all other parallels CI ran.

**Comment by Ocramius** [comment]
maybe https://github.community/t5/GitHub-Actions/continue-on-error-allow-failure-UI-indication/td-p/37033?

**Comment by greg0ire** [comment]
Setting this to false should do the trick: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast (but will affect the whole matrix)
