### ISSUE TITLE
Incompatibility to ocarmius/package-versions:1.10.0

### ISSUE THREAD

**Issue by alexander-schranz** [Ocramius/ProxyManager#617]
Currently at the `IdentifierSuffixer` class does access a not longer existing constant which was internal before of the ocarmius/package-versions library: https://github.com/Ocramius/ProxyManager/blob/2.8.0/src/ProxyManager/Generator/Util/IdentifierSuffixer.php#L50

Related Issue: https://github.com/Ocramius/PackageVersions/issues/147

**Comment by Ocramius** [comment]
I'll go ahead and write a fix for this right away 👍

**Comment by Ocramius** [comment]
Temporary fix at #617 - please review, @alexander-schranz :+1: 

I'll prepare another patch for `2.9.0`, so that `ocramius/package-versions` is completely phased out.

**Comment by Ocramius** [comment]
Workaround released @ https://github.com/Ocramius/ProxyManager/releases/tag/2.8.1

Working on #619 to get the dependency completely phased out.
