### ISSUE TITLE
Fix version for php 7.4.8 ???

### ISSUE THREAD

**Issue by tompuce** [Ocramius/ProxyManager#620]
This is the latest stable version of php. Is the next version of proxy-manager will be compatible with php 7.4.8 ? Soon ?
Thanks.

**Comment by Ocramius** [comment]
`ocramius/proxy-manager:^2.8.1` (and newer) is compatible with PHP 7.4.8:

https://github.com/Ocramius/ProxyManager/blob/371c8f2d9d1e888ce1f8f2137d9187252b07ee94/composer.json#L22
