### ISSUE TITLE
Issue when trying to push my repo on Heroku

### ISSUE THREAD

**Issue by cyr-il** [Ocramius/ProxyManager#633]
Hi, 
I'm trying to push my repo using Heroku CLI and i get this issue:
Your requirements could not be resolved to an installable set of packages.
      
         Problem 1
- Installation request for ocramius/proxy-manager 2.10.0 -> satisfiable by ocramius/proxy-manager[2.10.0].
- ocramius/proxy-manager 2.10.0 requires composer-runtime-api ^2.0.0 -> no matching package found.
         Problem 2
- ocramius/proxy-manager 2.10.0 requires composer-runtime-api ^2.0.0 -> no matching package found.
- doctrine/migrations 3.0.1 requires ocramius/proxy-manager ^2.0.2 -> satisfiable by ocramius/proxy-manager[2.10.0].
- Installation request for doctrine/migrations 3.0.1 -> satisfiable by doctrine/migrations[3.0.1].

I'm running Composer 2.0.7.
Can someone help me on this ?
thanks !

**Comment by Ocramius** [comment]
@cyr-il yeah, heroku does not yet support composer v2. See https://twitter.com/dzuelke/status/1327386646434770947

For now, I endorse doing a `composer update` with `composer:^1` locally.

**Comment by cyr-il** [comment]
@Ocramius Thanks for your help !! i'll do that
