### ISSUE TITLE
Deprecated: Function ReflectionType::__toString() is deprecated in C:\xampp\htdocs\pimcoredev\vendor\ocramius\proxy-manager\src\ProxyManager\Generator\Util\ProxiedMethodReturnExpression.php on line 19

### ISSUE THREAD

**Issue by niceguyblue** [Ocramius/ProxyManager#634]
I getting this error in php 7.4.12

Suggested fix : 

if (!is_null($originalMethod->getReturnType()) && 'void' ===  $originalMethod->getReturnType()->getName()) {
            return $returnedValueExpression . ";\nreturn;";
        }

**Comment by Ocramius** [comment]
What version of ProxyManager are you running? This should already have been fixed when PHP 7.4 compatibility was introduced last year, IIRC

**Comment by Ocramius** [comment]
Closing: this is indeed a duplicate of https://github.com/Ocramius/ProxyManager/issues/538#issue-537410218
