### ISSUE TITLE
PHP 8 install Problem

### ISSUE THREAD

**Issue by nrtszr** [Ocramius/ProxyManager#650]
i use xampp php 8 localhost

i write it comand line

`composer create-project symfony/symfony full`

Creating a "symfony/symfony" project at "./full"
Installing symfony/symfony (v5.2.1)
  - Downloading symfony/symfony (v5.2.1)
  - Installing symfony/symfony (v5.2.1): Extracting archive
Created project in D:\xampp\htdocs\symfony\full
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - ocramius/proxy-manager[2.7.1, ..., 2.7.x-dev] require php 7.4.0 -> your php version (8.0.0) does not satisfy that requirement.
    - ocramius/proxy-manager[2.8.0, ..., 2.11.x-dev] require php ~7.4.1 -> your php version (8.0.0) does not satisfy that requirement.
    - ocramius/proxy-manager[2.1.0, ..., 2.1.1] require php ^7.1.0 -> your php version (8.0.0) does not satisfy that requirement.
    - ocramius/proxy-manager[2.2.0, ..., 2.2.3] require php ^7.2.0 -> your php version (8.0.0) does not satisfy that requirement.
    - ocramius/proxy-manager[2.3.0, ..., 2.5.2] require php ^7.4.0 -> your php version (8.0.0) does not satisfy that requirement.
    - ocramius/proxy-manager[2.6.0, ..., 2.7.0] require php 7.4.* -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires ocramius/proxy-manager ^2.1 -> satisfiable by ocramius/proxy-manager[2.1.0, ..., 2.11.x-dev].

How to fix it?

https://prnt.sc/wc27dz

**Comment by Ocramius** [comment]
This library does not yet support PHP 8: you can install it at your own risk with the `--ignore-platform-req=php` flag
