### ISSUE TITLE
Cannot use non-nullable properties with AccessInterceptorScopeLocalizer

### ISSUE THREAD

**Issue by petr-buchin** [Ocramius/ProxyManager#682]
For now it's impossible to create proxies for objects that have non-nullable properties, even if that properties are being set in constructor.

Example:

```php
namespace Test;

use ProxyManager\Factory\AccessInterceptorScopeLocalizerFactory as ProxyFactory;

class Foo
{
    public function __construct(protected Bar $bar)
    {
    }
}

$factory = new ProxyFactory();
$foo = new Foo();

$factory->makeProxy($foo, [], []);
```

This code generates an exception:

```
[ProxyManager\Exception\UnsupportedProxiedClassException]                                                                                     
  Cannot create references for following properties of class Test\Foo: bar
```

Is this an expected behavior?

**Comment by Ocramius** [comment]
Yes, that is expected, since proxymanager needs a default value to exist
for these properties.

**Comment by petr-buchin** [comment]
@Ocramius as far as I see, this behavior can be fixed, if method `Properties::onlyNonReferenceableProperties()` will use constructor method reflection to see, what arguments does constructor have.

This way it can be sure that this properties will be initialized at the time of referencing them.

Do I understand that right?

If so, I could create a PR to address this issue.

**Comment by Ocramius** [comment]
ProxyManager cannot arbitrarily assign a value to those properties, and
they cannot be unset, unless a default value can be assigned by the tool.

Hence you need to modify your ctor to be `__construct(private ?A $a =
null)`, or declare the property explicitly, like we did pre-php-8.0.

Note that PHP 8.0 constructor signatures are automatically promoted to
property declarations: inspecting the constructor has no effect.

**Comment by petr-buchin** [comment]
> or declare the property explicitly, like we did pre-php-8.0.

@Ocramius I tried declaring property explicitly and having standard constructor with assigning this property a value, but that did not help

**Comment by Ocramius** [comment]
Sorry, I wasn't clear enough: the property must be nullable **and** have a
default value of `null` declared:

```php
private ?A $a = null;
```

**Comment by petr-buchin** [comment]
@Ocramius oh, that's too bad to declare all properties as nullable :(

But anyway, thank you very much for your help!

**Comment by Ocramius** [comment]
Yeah, it's a limitation that has been in place since PHP 7.4.

Note that decorator proxies still operate well with that.

**Comment by petr-buchyn** [comment]
@Ocramius unfortunately I need to use this kind of proxies, because I need to intercept method calls on $this, and they are not intercepted by value holder proxy. 

What do you think about creating a proxy type that will be similar to scope localizer, but will use Closure::call() to access properties instead of direct references?

It probably would be slower, but it will have it’s use cases. 

I would be happy to implement that kind of proxy in this library instead of creating another one.

**Comment by Ocramius** [comment]
I'm not aware of a way to make property access transparent, without
unsetting properties: if you have an idea/prototype on how to re-implement
this kind of proxy, feel free to propose a prototype, but please do test it
against the integration tests 😅
