### ISSUE TITLE
Compatibility to composer broken?

### ISSUE THREAD

**Issue by 4d4ch4u32** [Ocramius/ProxyManager#704]
I have a Symfony 3.4 project and I have updated it with `composer update`. The update was not successfull. Error message:

```
Fatal error: Uncaught Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "getAllRawData" of class "Composer\InstalledVersions".
  Did you mean to call "getRawData"? in /var/www/app/vendor/ocramius/proxy-manager/src/ProxyManager/Generator/Util/IdentifierSuffixer.php:51
  Stack trace:
  #0 /var/www/app/vendor/ocramius/proxy-manager/src/ProxyManager/Generator/Util/IdentifierSuffixer.php(39): ProxyManager\Generator\Util\IdentifierSuffixer::loadBaseHashSalt()
  #1 /var/www/app/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/PropertyGenerator/PublicPropertiesMap.php(25): ProxyManager\Generator\Util\IdentifierSuffixer::getIdentifier('publicPropertie.
  ..')
  #2 /var/www/app/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/LazyLoadingValueHolderGenerator.php(61): ProxyManager\ProxyGenerator\PropertyGenerator\PublicPropertiesMap->__construct(Object
  (ProxyManager\ProxyGenerator\Util\Properties))
  #3 /var/www/app/vendor/symfony/symfony/src/Symfony/Bridge/ProxyManager/ in /var/www/app/vendor/ocramius/proxy-manager/src/ProxyManager/Generator/Util/IdentifierSuffixer.php on line 51
```

There is a file `vendor/composer/InstalledVersions.php` in my project which is called from `\ProxyManager\Generator\Util\IdentifierSuffixer::loadBaseHashSalt` - in this method, there is a wrong method called (`getAllRawData()` instead of `getRawData()`). After manual fixing, it works.

**Comment by Ocramius** [comment]
Heyo, indeed you need o upgrade to `composer/composer:2.0.14` or newer: https://github.com/Ocramius/ProxyManager/blob/6046a5730a8d329d7f3d9c5239bc1c806512a854/composer.json#L28

See also https://github.com/Ocramius/ProxyManager/pull/700#issuecomment-847843483

**Comment by Venorcis** [comment]
@Ocramius I have the same error on composer 2.0.8 in a Docker container. Could you perhaps revert the latest commit in master, keeping the check of getAllRawData vs. getRawData intact?
