### ISSUE TITLE
getAllRawData not found in InstalledVersions

### ISSUE THREAD

**Issue by anarbekb** [Ocramius/ProxyManager#710]
Hello

I get error in CI/CD
`
In IdentifierSuffixer.php line 51:                                                                      
Call to undefined method Composer\InstalledVersions::getAllRawData() 
`

versions:
php - 7.4
ocramius/proxy-manager - 2.12.0
composer - 2.0.8

In InstalledVersions version 2.0.8 I didn't find a method getAllRawData

Can you help me please?

**Comment by Ocramius** [comment]
Hey there,

You should upgrade to latest composer

**Comment by anarbekb** [comment]
I can't update all my services at once to the latest composer, is there another way to fix the problem?

**Comment by Ocramius** [comment]
The alternative is locking to ocramius/proxy-manager to 2.11.1.

Due to an upstream BC break, the code was changed to use
composer/composer:^2.1, but it didn't go as planned, since the conflict
clause with old composer releases isn't working.

**Comment by Ocramius** [comment]
Closing here: an upgrade to latest version is the safest approach, but workarounds have been provided.
