### ISSUE TITLE
Undefined class constant 'VERSIONS' 

### ISSUE THREAD

**Issue by rela589n** [Ocramius/ProxyManager#712]
Package version: 2.2.3

There's incompatibility with ocramius/package-versions:1.11

Undefined class constant 'VERSIONS' in /var/www/vendor/ocramius/proxy-manager/src/ProxyManager/Generator/Util/IdentifierSuffixer.php on line 48

I saw #617 , however this AFAIK this bugfix goes only into version 2.8. Probably it should be fixed for previous minor versions as well.

**Comment by Ocramius** [comment]
Heyo,

`2.8.x` is really old, and `2.9.0` already fixes the problem overall.

Pinning to an older `ocramius/package-versions` is a better solution, if you are stuck.

Old `ocramius/proxy-manager` versions only get fixes if there's a security issue: https://github.com/Ocramius/.github/blob/6d4561515513f6d59fb144d838971d4a7715e3e4/version-support.md#support-policy
