### ISSUE TITLE
Bug in psalm annotation or in readme

### ISSUE THREAD

**Issue by vjik** [Ocramius/ProxyManager#713]
[Here](https://github.com/Ocramius/ProxyManager/blob/b19ebfd0d849857cfdface555e00ea2ba2109185/src/ProxyManager/Factory/LazyLoadingValueHolderFactory.php#L37) returned boolean value:

```
@psalm-param Closure(
  RealObjectType|null=,
  RealObjectType&ValueHolderInterface<RealObjectType>&VirtualProxyInterface=,
  string=,
  array<string, mixed>=,
  ?Closure=
) : bool $initializer
```

In [readme](https://github.com/Ocramius/ProxyManager/blob/2.14.x/README.md#proxy-example) `$initializer` doesn't return anything:

```php
$factory = new \ProxyManager\Factory\LazyLoadingValueHolderFactory();

$proxy = $factory->createProxy(
    \MyApp\HeavyComplexObject::class,
    function (& $wrappedObject, $proxy, $method, $parameters, & $initializer) {
        $wrappedObject = new \MyApp\HeavyComplexObject(); // instantiation logic here
        $initializer   = null; // turning off further lazy initialization
    }
);
```

**Comment by Ocramius** [comment]
@vjik indeed, can we adjust the readme?

**Comment by vjik** [comment]
> @vjik indeed, can we adjust the readme?

In [docs](https://github.com/Ocramius/ProxyManager/blob/2.14.x/docs/lazy-loading-value-holder.md#usage-examples) in example returned true.

**Comment by Ocramius** [comment]
Yes, I mean, can you send a patch for https://github.com/Ocramius/ProxyManager/tree/b19ebfd0d849857cfdface555e00ea2ba2109185#proxy-example ? :D

**Comment by vjik** [comment]
I don't know how to right :(
Need with return or need w/o return.

**Comment by Ocramius** [comment]
The correct notation is **with** return

**Comment by vjik** [comment]
https://github.com/Ocramius/ProxyManager/pull/714
