### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by Jeckerson** [Ocramius/ProxyManager#716]
Hello. We are using this package in Zephir and currently we are trying to see if Zephir C code is compatible with PHP 8.1-beta.2.

By using `composer update` occur next error:
![image](https://user-images.githubusercontent.com/3289702/128562752-3b93884b-3291-4dea-9546-6982fafc058f.png)

**Comment by Ocramius** [comment]
Heyo,

I will start working on PHP 8.1 support **after** the first RC land (sometime in September).

**Comment by blankse** [comment]
Still no PHP 8.1 support?

**Comment by Ocramius** [comment]
Correct, still some upstream dependencies required: https://github.com/laminas/laminas-code/milestone/19

**Comment by tigran-m-dev** [comment]
@Ocramius still no PHP 8.1 support. Any estimation on this?

**Comment by Ocramius** [comment]
No estimation: haven't had time to work on it, and the coming weeks don't look much better either.

I've done the work to get `laminas/laminas-code` updated (and released), and worked on some bugs related to PHP 8.1 (notably #754), but there is still a lot in the milestone to call PHP 8.1 "supported": https://github.com/Ocramius/ProxyManager/milestone/56

**Comment by mikemberg** [comment]
still no PHP 8.1 support... is PHP 8.0 working?

**Comment by Ocramius** [comment]
8.0 works

**Comment by francescodimech** [comment]
any idea on date for support on php 8.1?
