### ISSUE TITLE
Evaluate chance to skip calling parent methods when logic is fairly simple

### ISSUE THREAD

**Issue by Ocramius** [Ocramius/ProxyManager#77]
When the logic of a method (for example a getter or a setter) is fairly simple, we can skip calling the parent method and just copy-paste the logic in the child class.

That's very dangerous though, and may need some evaluation.

**Comment by nmeri17** [comment]
This is exactly what I need right now. I want to control invocation of the parent method. If I do that on the concrete instance on the pre hook of value holder factory, changes within the hook to the instance don't propagate to the proxy. If I use the proxy instead, or replace value holder with scope localizer factory, the terminal where I'm running the tests crashes every single time. I've never seen anything like it. Is there any way to sync both objects so callers who receive proxy can read updates made within the wrapper, while letting me control invocation? Specific use case is wrapping invocation in a try catch after running some other logic

**Comment by Ocramius** [comment]
@nmeri17 let's please turn this discussion into a new issue, with code examples, please :D 

 > he terminal where I'm running the tests crashes every single time

Sounds like a bug :D

**Comment by nmeri17** [comment]
> @nmeri17 let's please turn this discussion into a new issue, with code examples, please :D
> 
> > he terminal where I'm running the tests crashes every single time
> 
> Sounds like a bug :D

Done https://github.com/Ocramius/ProxyManager/issues/762. Thanks for your prompt response BTW
